### ISSUE TITLE
report witchery modpack v1.1 alpha 

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#1]
-only one puppet work after you finish one even if you just tried one the rest will be skiped
-letter to dursts -missing from hidden skeleton room
-death house-return to the church won't get finished with given held item`
-father donavich stock on making distillery even after craftinh it `
(npc quest and the book complete their quest but none of the npcs get the trigger)
-unloking the altar-mary will not be triggered

**Comment by teagan75** [comment]
Is the better questing book skipping poppet quests or custom npcs?

**Comment by satanKami** [comment]
the custom npc marry skip to find her missing child
(i just clicked earth puppet finished it and then there was no water or fire)

**Comment by teagan75** [comment]
Took me a bit but I realize I attached the wrong dialogue to Mary. It’s fixed for next update along with the other issues. Probably tomorrow. Thanks for all the help.

**Comment by satanKami** [comment]
np i said ill help till the end btw can you guess who i am?~youtube

**Comment by teagan75** [comment]
Now you put me on the spot! Lol. I can safely assume this isn’t your YouTube name ha. So I will take a guess and say DarkRaikon??? 🤷‍♀️ The two names fit

**Comment by satanKami** [comment]
you are correct!! you won the game 
btw im using mc edit to copy my items from each save so you never lose stuff

**Comment by teagan75** [comment]
Changes made in version 1.2-alpha
