### ISSUE TITLE
report on 1.2 alpha 

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#11]
-madam eva-after making the kettel she stoped from talking cause...there is no more dialog other then kettle
-tried to finish thou the quest book madam quests to unlock the bonegrinder but it didnt worked..
-hung man wont say anything even after you use the lever
-vallaki-has no other lines(just find that place)
-the carpet ladders and hatch are there  in this pack(unlike in the episode)-but the door wont budge.

**Comment by teagan75** [comment]
Will check on Madam Eva
Hung man shouldn’t say anything. He is hung lol
Vallaki has some new quests if you are on version 1.3 and run command /bq_admin default load

I will check the door in the attic again

**Comment by satanKami** [comment]
is 1.4 need another save?

**Comment by teagan75** [comment]
I fixed all the bugged quests. I did a fresh play through to see what was actually happening so I think it will work now in version 1.4
