### ISSUE TITLE
1.3-alpha  Et Futurum replaced a couple of blocks

### ISSUE THREAD

**Issue by ScyphozoaIV** [teagan75/Witchery#12]
Et Futurum has replaced enchanting tables with brown mushroom blocks and brewing stands with birch fences, in the map. They could just be for aesthetics but, I never got very far in witchery, so I'm not sure how important they are for the pack.

**Comment by teagan75** [comment]
Ok then I will need to replace out the level.dat in the template folder

**Comment by teagan75** [comment]
Level.dat has been replaced in the template folder in version 1.4
