### ISSUE TITLE
report 1.3

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#13]
-mad marry still just one puppet-maybe make it a choice option`
-father wont get trigger to active quest curing doru
-madam eva wont be triggered when player nearby so no quest at all

**Comment by teagan75** [comment]
Did you start a new map?

**Comment by satanKami** [comment]
always 
i just bring back my stuff so i can make a quick checkup(mc edit)

**Comment by teagan75** [comment]
Really hope I fixed all this. I did a fresh play through to see what was actually happening so I think it will work now.
