### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by LadyGrelka** [teagan75/Witchery#14]
Not sure if this is just Twitch being stupid, and that is a huge possibility, or something wrong with the download but I have been unable to download/install this pack for the last two weekends, I keep getting this error;   
![error 1](https://user-images.githubusercontent.com/18753583/33788716-9bb0719a-dc28-11e7-84c4-b87bdc3f8408.png)
I have closed everything internet related and tried to download/install again but that did not help. I was able to download/install another modpack, just not this was.

**Comment by teagan75** [comment]
I would put in a ticket to Curse. Go to help at top left
