### ISSUE TITLE
Alpha 1.4 Poppets again

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#15]
I'm not sure if anyone else is still having problems, but I still cannot get all three poppets completed with Mary. I talk with Mary and she asks me what poppet I'm interested in. I tell her earth. She tells me to make the poppet. I make it, I return to her and I get credit for making it, she gives me the option of Fire, water and what next. I click next she tells me to get the items of earth. I go get them and talk with her. She gives me credit and tells me to stuff the items in the doll and taglock it. She gives me taglock kit and chicken seeds. I go make the poppet and taglock it to me. I talk with her expecting the option of Fire and water and all she says again is Hello Ladysarajane. What am I missing? I thought I remember you going back after making it and she give you the option to make one of the other two left. 
My files are fresh with a new world.

**Comment by teagan75** [comment]
Yep and I just played thru it again. I have no idea what is going on when uploading my files 🙁

**Comment by Ladysarajane** [comment]
Yeah, I deleted all the old files and installed the ones that are supposed to be 1.4. Started a new World so there is no old data from previous playthroughs. I'm used to Better Questing but not experienced with NPC questing. I was thinking I was missing something and I watched your poppet video again for the steps.  There should be a taglock kit for each poppet completed from Mary, correct? And I think dye seeds for one of the poppets?

**Comment by teagan75** [comment]
Yep

**Comment by LadyGrelka** [comment]
I too am still having problems with the poppet quest line, under the Bloodvine line I have completed through Unlocking the Alter, for the poppet I still need water and fire, but all she says is "Hello Kestrah".

**Comment by teagan75** [comment]
Mad Mary is beginning to piss me off :P

**Comment by Ladysarajane** [comment]
Mad Mary's madness is rubbing off. ;)
Suggestion:
What if for the time being, Have Mary do the basic poppet and earth poppet ( those seem to be okay together) end that quest in one line, then have Mary look for the finished fire and water poppers next with her saying bring those to her. That way she could give the rewards and Advance to the next quest. The better quest book has the items listed for each poppet.

**Comment by LindaJuffermans** [comment]
Maybe she's got too many quest lines... it's the pressure... that's why she's crying...

**Comment by LadyGrelka** [comment]
I am going to use this time waiting for Mad Mary to stop being a pest to try to get my alter power set up, I hope lol.

**Comment by Ladysarajane** [comment]
Teagan, in more testing, I was able to start the quests with the command line, and finish it normally with Mary. I received all rewards normally with Mary then, it is just the initiation of the last two poppet quests that is the problem.  Better than 1.2 version... On the right track there, just need to find the right train. :)

**Comment by LadyGrelka** [comment]
Ladysarajane, you said you where able to start the quests with the command line, could you tell me what to type in?

**Comment by Ladysarajane** [comment]
in the chat, I typed  /noppes quest start ladysarajane 13  and that started the fire poppet, then I typed in /noppes quest start ladysarajane 14  and that started the water poppet. I am assuming the earth poppet is probably 12.  After I started it,  I collected the materials that are listed in the better questing list and showed them to Mary. She gave me my reward, I made the poppet and taglocked it and started the next quest to repeat.

**Comment by LindaJuffermans** [comment]
We had the same issue; resolved using the same commands. It seemed like the 3rd steps (the actual poppets) in the questbook was already completed btw.

**Comment by teagan75** [comment]
The poppet completion in the book is a limitation. All poppets have the same id

**Comment by satanKami** [comment]
maybe just make it an choice option and the book explain the other puppets
like you need this for earth poppet:
like you need this for water poppet:
like you need this for fire poppet:
the book just ask for 3 puppets and the npc ask what puppet do you wish for then the
what now...and done 

after all i did one puppet the book can tell me how to make all the other 2

**Comment by teagan75** [comment]
hopefully this is fixed now in version 1.5
