### ISSUE TITLE
No Tent at beginning and it surely isn't peaceful. 

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#16]
Still no tent when spawning in the world. Also my settings are not peaceful when spawning in. It is set to normal. I have been smacked by zombies, skeletons and creepers on the way to Mary's, during the day. Big hole in the road, outside of Ireena's mansion from a creeper.

**Comment by satanKami** [comment]
i may not spawn in peaceful and had to rest it but after that it was peaceful sorta...

**Comment by teagan75** [comment]
fixed map for version 1.5 (would require a restart to see changes)
