### ISSUE TITLE
Dead House missing entrance door.

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#17]
Finally got to the Dead House quest and when I went to talk to Rosavald Durst, even before talking to her, I noticed the Dead House had a door missing. Able to walk in the house without the key. Just to double check I started a new world and same thing.

**Comment by teagan75** [comment]
Weird. Something is definitely not loading up properly via Twitch app

**Comment by Ladysarajane** [comment]
After watching your Death house video again, I realized it wasn't a double door missing it is the grey wool on the house itself. 
![death house entrance](https://user-images.githubusercontent.com/34258851/33895795-4f0b5e54-df2f-11e7-835b-6081e4cc7fef.png)

**Comment by LindaJuffermans** [comment]
I was going to post the same thing :)

**Comment by teagan75** [comment]
map fixed for version 1.5 (would require a restart)
