### ISSUE TITLE
Father Donavich questline problem

### ISSUE THREAD

**Issue by LadyGrelka** [teagan75/Witchery#18]
I have completed Unlocking the alter and Special Distillery, but can't start Curing Doru or Talismans, I have bother ritual chalk and Golden chalk, he told me about making ritual chalk, and then after that about making golden chalk and doing the Rite of Sanctity and I did the Rite of Sanctity and went back to him and all he now tells me is I need some special chalk and about needing a distillery and needing a special stone to make it and to come back when I have the distillery, I have made this and still nothing. By the way I am playing in 1.4

**Comment by Ladysarajane** [comment]
I have not have had a problem with this. I do know you have to take each item to him including the distillery to complete them.

**Comment by satanKami** [comment]
haa... you need to go first show him the chalk then the ritual ...
the good and bad in teagan she ask and want to confirm every step you did
once you used the chalk he wont recognize it

**Comment by teagan75** [comment]
Haha. It’s a limitation with custom npcs and triggering the next quest. I could combine the two chalks into one and make it recognize partially used chalk.

**Comment by LadyGrelka** [comment]
Not sure I am getting this right, I took chalk (never used) and the distillery to him and still nothing.

**Comment by Ladysarajane** [comment]
I talked to Mary to get more info on the altar power. Took the distillery to Father Donovich. Went to make chalk. Talked to Mary again. Took both white unused chalk to Father Donovich. Then made the gold chalk. Took that to Father Donovich. He gave me rite to do. I left the church then went back in and he asked me how the rite went. I told him fine and he told me about the talismans.  In my second world I played it and did the rite without any problems, and made my talismans. Not sure what is missing. What is still open in your NPC log book?  
I had to rebound the quest log to a different key to see it and to keep the better quest book on the Tilda key. The NPC log book gives a better indicator what still needs to be done.

**Comment by teagan75** [comment]
If it worked on one world and not the next, then it’s the glitchy Custom NPC delay. Sometimes going to the npc again and trying to talk triggers it. Sometimes re-logging does it and sometimes it’s just stubborn and has to be pushed through. 

Did you answer Father Donavich about how the rite went? And he didn’t give you the next quest? If it’s just stuck, I will have to look up the quest number so you can push it through.

**Comment by Ladysarajane** [comment]
I had no problem Teagan, I was trying to help LadyGrelka figure out if she was missing something. The NPC quest log is a good place to see what still might be missing, but sometimes you can't open it because of key binding conflicts. I just know I had to talk to Father Donavich alot about it, and talk to Mary to get past it. It worked in both my worlds, with and without doing the ritual. I just answered it went fine in the world I didn't do the ritual. (My second world,  and I wanted to see if the ritual was really necessary)

**Comment by LadyGrelka** [comment]
Ok, here are three screen shots, one of my quest book, and one of the text with Donavich, take a look in my hotbar unused ritual chalk and gold chalk, and my distillery, the last one of the NPS quest tab.

![2017-12-16_09 24 07](https://user-images.githubusercontent.com/18753583/34072841-68d8ee16-e243-11e7-9178-ba5176d15004.png)
![2017-12-16_09 24 48](https://user-images.githubusercontent.com/18753583/34072842-68ffa0f6-e243-11e7-8d69-2b8ff3d4be94.png)
![2017-12-16_09 40 15](https://user-images.githubusercontent.com/18753583/34072972-649b2b00-e245-11e7-8bd4-f0d003925e22.png)

what did I do to break the game lol, I seems I can't do further or start quests where I have to talk to an NPC, or said NPC will not work right.  I went and tried to do the Madame Eva quest because its open now, and the only part it would show I did was finding the Vistani Camp, found and tried to talk to Madam Eva and nothing all she says is Hello, Stranger.  I am soo confused lol.

**Comment by satanKami** [comment]
you didnt do the ritual ..there is no quest to it he would just tell you to do it

**Comment by LadyGrelka** [comment]
I did the ritual as well, both of them, the Rite of Sanctity and the right of Binding, went back to him after each one and nothing.

**Comment by Ladysarajane** [comment]
Ritual doesn't make a difference if you do it or not. What interests me is the NPC quest log has advance to the curing quest and doesn't list the distillery quest or chalk quest. Did you update this world from 1.3 or is it a fresh set of 1.4 files? I'm just trying to figure out why it worked in mine and not yours. Mine was a fresh set.

**Comment by LadyGrelka** [comment]
Mine was updated from 1.3, I could try backing up my save, deleting the whole pack and reinstalling it fresh and then moving my save back over, its just installing mods on Twitch is a pain, constant time out errors, so I wanted to avoid that lol.

**Comment by Ladysarajane** [comment]
Yeah, I'm thinking that the save might have a glitch or the game files. I don't know if you can zip up your world and attach it here for me to try on my files. I'm wondering if those time out errors for you affected your files. Luckily I don't have a problem with downloads so I always use fresh  files. In this case I used new worlds too cause of the poppet quest.

**Comment by teagan75** [comment]
I can always put the files on github here but you would need to know how to install your own instance

**Comment by LadyGrelka** [comment]
I backed up my save, deleted ;the; modpack and re-downloaded it, no problems this time YAY, then put my save back and same problem. I guess my next option is to start a new save, unless there is a way to reset the questbook and then just push through the quests I have already finished, because starting al whole new world, mainly redoing my alter and power set up, would be a big pain and time consuming.

 I zipped my save but the file is too big to post here

**Comment by teagan75** [comment]
There is no easy way for custom npcs to push through quests

**Comment by teagan75** [comment]
You could just try deleting the playerdata file. The path is .minecraft/saves/world/customnpcs/playerdata

Then you won’t have to redo the altar or your base. Just rush through the quests again

**Comment by LadyGrelka** [comment]
I would just have to do the quests again, sounds better then having to set up everything all over again lol. I can deal with having to make everything again, I think lol. Now would that just be the NPC quest stuff I would have to redo, or would I have to redo all the quest in the questbook again as well?

**Comment by teagan75** [comment]
Just the npc ones. If that doesn’t work you might have to replace the whole custom npc folder in the save file with the one in the template folder. But hopefully it will trigger for you correctly

**Comment by LadyGrelka** [comment]
Well, I deleted the NPC playerdata like you suggested, got stuck on the poppet quest again lol, and got to the same spot with Father Donavich and he is back to being stuck on the same dialog as before.

I will try replacing the whole custom npc folder, once I find the template folder that is lol.

**Comment by LadyGrelka** [comment]
Ohhh think god, replacing the whole custom npc folder worked, and I am ignoring the uncompleted Dead House quest that wants a key lol, but got Mad Mary to not only give me the Finding Gertruda quest but I got the Curing Doru quest and finished the talismans quest as well. *Happy dance!*

**Comment by Ladysarajane** [comment]
Glad you fixed it!

**Comment by teagan75** [comment]
hopefully no more issues with version 1.5 :)
