### ISSUE TITLE
1.4-alpha - Secret door attick exposed

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#19]
![2017-12-12_15 23 26](https://user-images.githubusercontent.com/31929183/33906589-a463864e-df82-11e7-9ec8-7c5bd7d2dcb6.png)

Even before talking to Dora, when we came up the stairs to the attic we could see the secret door.

**Comment by satanKami** [comment]
yup...she need to lower the redstone trigger to be closer to there
and maybe sign dollhouse...

**Comment by teagan75** [comment]
fixed on map for version 1.5 (would require a restart)
