### ISSUE TITLE
Wolves

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#2]
I don't know if their spawnrate has changed but at any given time I'm surrounded by 20 wolves on the minimap and I'm often fighting 4 or more at a time (day or night). Luckily the game is still "very easy" so they don't do any harm yet. I've also encountered a large amount of those glitching wolves that move at great speed.

**Comment by teagan75** [comment]
Ok. I will take down the spawn rate. They are the same as zombies.

**Comment by satanKami** [comment]
tip once it get easy you may want diamond armor cause servent type will 3 hit k.o you.. thats from the mod itself

**Comment by teagan75** [comment]
The "glitching" wolves are blights. I may just turn them off completely. Blights are invisible, 3x health, and on fire with super speed lol

All of these changes will be in version 1.2-alpha
