### ISSUE TITLE
1.4-alpha - Madam Eva questline "Brew of Webs"

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#20]
We completed "Spinning Threads", the last step was to talk to Madam Eva. For the next questline "Brew of Webs" we need to talk to her again but she only says "Hello, stranger".

**Comment by teagan75** [comment]
Lol ugh I commented on why I think this is happening but my changes weren’t transferring to you

**Comment by Ladysarajane** [comment]
I too am experiencing this.

**Comment by LadyGrelka** [comment]
I too am having this problem, and just when I got my other quest problems worked out lol.

**Comment by teagan75** [comment]
hopefully this is fixed now in version 1.5
