### ISSUE TITLE
1.4-alpha - Baroness quest

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#21]
After talking to Victor (first time), when the conversation is done we got a quest complete dialog "Speak to the Baroness" - but we haven't talked to her. When we do, she only says "Hello, stranger"

**Comment by teagan75** [comment]
I think I may know why there is a disconnect and things aren’t saving. I updated the client but never updated my instance with the newest Custom npc. I can finally clone again so I will release a small update for everyone that hopefully saves the changes I have made and never transfer

**Comment by LindaJuffermans** [comment]
Will we have to restart or can I clone her too?

**Comment by teagan75** [comment]
She will be cloned. However I played through again and everything was fine on my end still. So I am thinking it was the two versions. I hope we can finally put some of these issues behind us lol

**Comment by teagan75** [comment]
hopefully this is fixed now in version 1.5
