### ISSUE TITLE
1.4-alpha - Not peaceful after 1st startup

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#22]
The first time we started and joined the server it was in peaceful mode; subsequent restarts the server wasn't in peaceful (I can't tell if it was easy or normal).

**Comment by teagan75** [comment]
It will only be in peaceful until you restart. There is no way around it since those settings are controlled by client. I can run a command and then it goes back to client settings or server settings on restart.

**Comment by teagan75** [comment]
if this happens again when you start a new game  just run command /bq_admin reset all
