### ISSUE TITLE
1.4-alpha - mobGriefing ignored

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#23]
Unless it's intended - even after disabling mobGriefing, creepers blow up and destroy blocks.

**Comment by teagan75** [comment]
I have noticed this

**Comment by teagan75** [comment]
I wanted to keep Creepers and Endermen out of the pack because they don’t fit the theme but I would have to figure a way for players to obtain creeper hearts

**Comment by ScyphozoaIV** [comment]
You could add a custom recipe. I believe this would require adding minetweaker though.Make the creeper seeds a reward, if they aren't already. The Regrowth pack has a recipe that for eight creeper essence makes one creeper heart. Fill the entire 3x3 crafting grid except the top left corner. You could even make it a cauldron recipe - gunpowder (which I think can be crafted with the essence), mutandis, squid ink (it's shaped a bit like the hearts) and of course altar power. It shouldn't be too expensive but can't be cheep either, maybe at least two or three thousand.

**Comment by LindaJuffermans** [comment]
What ScyphozoaIV said 🙂

**Comment by satanKami** [comment]
you can config mob drop that some mobs can drop other items -with commend i used to make blazes drop snowball for a game
i can try to look for that command but it was 1.6.4i think

**Comment by Ladysarajane** [comment]
Just a note on Alpha 1.6.2.  I had started a new world to go over some of the previous things to make sure they were fixed...poppet quest, Ireena dialog no creepers spawning etc. I hadn't seen any creepers until it was time to go into peaceful mode to do the Dead House again. Once I was done with the dead house, I went to put my pack back into normal mode and all of a sudden all of these creepers spawned everywhere as soon as I did.....but it was hilarious, I could walk right through them. They followed me, but they never exploded and I could not touch them.  When I restarted the pack, it was back to normal, no creepers spawning. So just a word of warning, restart pack when changing modes. LOL. It is nice not to have those creepers exploding everything around.

**Comment by satanKami** [comment]
yeah every update do new map

**Comment by teagan75** [comment]
Ghost Creepers. That’s a new one lol

**Comment by Ladysarajane** [comment]
Yeah, My heart stopped when one first approached me, I was expecting that hsss BOOM, but it never came. At least I am back into the dream world looking for those dang diamonds again...Everything works so far. :)

**Comment by teagan75** [comment]
That is good to hear!

**Comment by satanKami** [comment]
sound like a good mod! ghost creeper
also i found those mods you may want to see...
http://www.9minecraft.net/nightmare-creatures-mod/
http://www.9minecraft.net/crackedzombie-mod/

**Comment by teagan75** [comment]
I have dealt with the Creepers in 1.6.2
