### ISSUE TITLE
1.4-alpha - Vallaki questline

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#25]
We talked to Victor, made the otherwere chalk and the waystone. Questbook mentions Glowstone and Ender Dew (tho Victor didn't) which we also got.

- When we talk to the Baroness she just says "Hello stranger" (actually the questbook already said that quest was done).
- When we talk to the Baron he starts talking about the festival again; for me a new quest "Teleport" opened, for my friend it didn't.

**Comment by teagan75** [comment]
I am hoping to get another update out soon. Hopefully today. You won’t need to restart. Since everything is working fine on my end it should transfer properly now.

**Comment by teagan75** [comment]
Teleport opening up for one and not the other is a common occurrence due to server client communication. Sometimes it will trigger if you go back to the quest person and talk to him. This case Victor.

**Comment by teagan75** [comment]
hopefully this is fixed now in version 1.5
