### ISSUE TITLE
1.4-alpha - Milivoj

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#26]
When we talk to Milivoj he just says "What do you want" and we don't have a line to respond. I've tried right-clicking him with bread in my hand, I've thrown bread at him, he doesn't take it and we cannot continue.

**Comment by teagan75** [comment]
You threw bread at him?! Well now he will never talk lol :P

**Comment by LindaJuffermans** [comment]
I even tried punching him with bread but it seems I cannot harm him... 😅 Seriously tho, am I doing something wrong or is this line not finished yet?

**Comment by teagan75** [comment]
It’s finished on my end. Really hoping the next update transfers properly. I think I may use the the way I offer downloads for Fate of Gods

**Comment by Ladysarajane** [comment]
Yep, I tried it too and he won't take the bread. I was thinking maybe the files are not updating properly when you download the updates from twitch, but I have a clean install, and I am experiencing the same thing.

**Comment by teagan75** [comment]
hopefully this is fixed now in version 1.5
