### ISSUE TITLE
Kettle Rewards

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#27]
Teagan, I know in Your Youtube videos, you mentioned adding nether seeds to the rewards for finishing the kettle. Do you still plan to add that? I really want nether quartz to make a drawer controller. :)

**Comment by teagan75** [comment]
I added seeds in but they might be later on and in the Dream world. I will double check

**Comment by Ladysarajane** [comment]
Thank you Teagan. I am really enjoying playing this. I just wish I could figure out how to get rid of the bats in the house across from Mary's. I'm living there and they get in the way...LOL. Right now I have about 30 bat wools from them.

**Comment by teagan75** [comment]
Ha there is a command block in there. I should stop bats there since I suggest it as housing lol

**Comment by satanKami** [comment]
Ladysarajane  near the end where there is that "wooden tv" or idk how to call it where teagan placed her crafting table break there (around it to find redstone and command block break one of them to get rid of the bats)

**Comment by Ladysarajane** [comment]
I just can't find that stupid block. Gonna have to find a cat to take care of them ;)

**Comment by teagan75** [comment]
There is a pet shop in Vallaki 😉

**Comment by Ladysarajane** [comment]
Gotta find that shop!!!  My luck the cat will be lazy and won't chase them.. LOL

**Comment by satanKami** [comment]
i didnt found the pet shop....search for a wolf and then after i tamed it ...the quest wanted a spawn egg..so i creative it

**Comment by satanKami** [comment]
i didnt found the shop..even went creative to fly and find it but i adopted the tigress to be my pet ^_^

**Comment by teagan75** [comment]
Next update will have nether seeds as a reward for the kettle

**Comment by teagan75** [comment]
added in version 1.6
