### ISSUE TITLE
Alpha 1.5 Poppet Quest

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#28]
Fresh files, download, new world. Tent is now present, Dead house repaired...but poppet quest will not trigger for the second two poppets again. After I finish the earth one and go back to Mary she just says "Hello Ladysarajane" instead of offering one of the other two. 

Maybe I am doing this wrong. I talk to Mary.  
1. She asks me what poppet I am interested in. I pick earth. She tells me how to make a basic poppet and come back to her. 
2. I do and return and she is happy.  Now she lists  water, fire and what is next.
3.  I chose what is next? She tells me to collect the items for earth and return. 
4. I do and show them to her and she gives me chicken seeds and tag lock kit.  I plant the seeds and taglock the poppet and when I return to her all she says is "Hello Ladysarajane"

Am I doing it wrong? I thought I remember you doing them one at time.

**Comment by teagan75** [comment]
Can you try downloading the files via the download button on the main menu for minecraft. I want to see if something is corrupting

**Comment by Ladysarajane** [comment]
It will take me a bit, but I will try and let you know how it goes. My uncle just went to the hospital and I can't visit him, cause croup is in the family, so I'm playing phone tag with my cousins trying to find things out.

**Comment by Ladysarajane** [comment]
I downloaded the files, and tried it with an existing world that had not reached the poppet stage yet. I will download a new instance of 1.5 and download those files again, then start a new world to see if that works. I watched your making poppet video and those are the steps I took.  I'm getting good at starting up! Only thing that hangs me up is looking for crazy Wolfbane seeds. Really should charge the town for lawn work. 
 Love the tent and chest. Thank you, it does add to the feeling of awaking there.

**Comment by Ladysarajane** [comment]
Okay, new files and downloaded the files on the download file on the main menu to see if that was the problem with twitch. Get stuck at the same place. I downloaded the files from here,  Found where they go in minecraft but still get stuck at the same place. Not sure why the NPC's are sticking. I took the old Mary NPC file deleted it and manually put in the new one from file 2.

**Comment by teagan75** [comment]
Can you try the clone? Get the cloned tool out of creative and use it. Select tab 2

**Comment by Ladysarajane** [comment]
Okay...had to try to figure out this cloner tool. I got the NPC wand and cloner tool. I deleted "Mary" with the NPC Wand and then used the Cloner tool and spawned her in from Tab 2. Still no go. Since I had already triggered part of this quest, It may not work now. What I will do is get a fresh world, and try to clone her in from the beginning and see if that affects anything. I won't have too much time to work on this today. MUST BAKE COOKIES. Teagan if you celebrate Christmas, "Merry Christmas" to you, JJ and your hubby. I have a JJ also. He is my 12yo nephew. 
I will let you know how it goes!

**Comment by Ladysarajane** [comment]
Started with fresh files again. Ran into the same problem. I used the Clone from tab 2 and I still could not advance.

**Comment by teagan75** [comment]
I am at a loss as to what is causing this

**Comment by Ladysarajane** [comment]
I pushed the quests through by starting with command. Once you start each one, they finish, but you have to start  the two poppets. I will work to madam Eva, to see if I have trouble with the brew of webs. Reports that I read cloning her works. I'll see if I can successfully do that.

**Comment by Ladysarajane** [comment]
I was able to start brew of webs this time without cloning Madam Eva.

**Comment by satanKami** [comment]
same..the problem as i see it that once you finished one it wont switch to the other two...
maybe you need a line of ïve did all 3 what now?"

**Comment by teagan75** [comment]
Every time I test I don't run into this issue at all but I have gated the quest now for the next update. I hope this will fix the issue.

**Comment by Ladysarajane** [comment]
Willing to test again.

**Comment by teagan75** [comment]
Let's hope this is finally resolved in version 1.6
