### ISSUE TITLE
Morgantha

### ISSUE THREAD

**Issue by LadyGrelka** [teagan75/Witchery#29]
I am at the Bonegrinder and have spoken to Morgantha but after she tells me the secret ingredient is from the dream world I have no options, just like in your video, when you said you forget to connect the dialog.

**Comment by teagan75** [comment]
Will check that. Is this version 1.5?

**Comment by LadyGrelka** [comment]
Ya, its 1.5

**Comment by Ladysarajane** [comment]
I encounter this also.

**Comment by LindaJuffermans** [comment]
I fixed this with the NPC wand by linking the "Morgantha V" dialog to the dialog option.

**Comment by Ladysarajane** [comment]
I did that, and got the quest for the sleeping potion, but the conversation doesn't flow. Is there any other dialogs I should add to the dialog? After I completed it, she gives me the rewards, but doesn't say anything else and no new NPC quest shows up.

**Comment by teagan75** [comment]
I hope to have time to fix this in the next couple days

**Comment by Ladysarajane** [comment]
Okay, I did the brew of sleeping, took the potion to Morgantha and she gave me the rewards of the cow and nature seeds. Now she keeps repeating the sleeping potion quest dialog, and I can't move forward with her. I did drink the sleeping potion and got the disturb cotton which registered in the better questing book, but not the fact that I took the potion and went to the dream world. There is no Bonegrinder quests open in the NPC quest log . Any suggestions on how to advance Morgantha in her dialog? 
 Teagan I hope JJ is feeling better.  Rough time to be sick for a little one and Momma. Oh, Happy New Year!

**Comment by LindaJuffermans** [comment]
After linking the dialog option, the remainder of the quests seems to work fine. We're now tasked with making that brew in the dream world.

**Comment by Ladysarajane** [comment]
A guess I'm out of luck for now. Can't get her to advance, and better questing won't recognize I've gone in the dream world despite that I picked like 5 disturbed cotton before the nightmare got me.

**Comment by teagan75** [comment]
She shouldn't be repeating the sleeping potion dialogue at all. Nothing is wrong in my dev instance for that. It is gated. I did fix the dialogue issue in the dev instance for the next update. 

If you completed the Dream Catchers quest, then the next quest should have triggered. If it didn't run command /noppes quest start [your name] 45

**Comment by Ladysarajane** [comment]
Okay, quest 45. I didn't know which one it was.

**Comment by teagan75** [comment]
no problem :)
