### ISSUE TITLE
Poppets Version 1.2-alpha

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#3]
I did the earth poppet without problem, Mary continued and let me start the fire one, when I went to finish it and talk to her with the ingredients, All she says is "Hello Ladysarajane."  I cannot complete it, or move to the next one. I did also try the ingredients for the water one also, but she says the same thing.  I did delete my old profile and download the version and started a new world for this.

**Comment by teagan75** [comment]
I will check in what happened with that quest. At least that won’t require a map reset 😁

**Comment by teagan75** [comment]
On my end, nothing seems out of place. However, I did see that the quest had ignore damage flag on. Maybe that is the issue. I will push an update soon, but for now type /noppes quest finish <your name> 13 and then repeat for quest 14 so you can move on

**Comment by Ladysarajane** [comment]
Okay, I tried to type in the chat box  /noppes quest finish 13 and it told me there was no such quest. I believe the earth poppet is suppose to be quest 11,  water poppet quest 12 and the fire poppet quest 13. That is the info I get when I shift click over it in the quest book, to find info. I have started another world to see if I have the same problem.

**Comment by teagan75** [comment]
Oh thats right you never got it started. You would have to first type  /noppes quest start 13 and then  /noppes quest finish 13 and repeat for 14

The questbook has different numbers than the actual npc quest

**Comment by Ladysarajane** [comment]
Still no go. I typed /noppes quest start 13 and still received the error that there is no quest. Tried it start 14 and received the same error. This happened in two worlds.

**Comment by teagan75** [comment]
Well that is very strange. My dev instance that I gave everyone has those quests. Can you try switching your name with the quest number? It’s like it is saying your name isn’t a quest.

**Comment by Ladysarajane** [comment]
Okay In my one world I was able to start quest 13 which was the fire poppet one by typing /noppes quest start ladysarajane 13. I was able to finish the quest normally then.  I tried to start the water poppet quest which I was able to start with typing /noppes quest start ladysarajane 12 and it started it, however I could not complete it with Mary like I did the fire poppet one. I had to type /noppe quest finish 14 to complete it, but I did not get the taglock kit from Mary. I have been able to start the next portion with Mary. Tomorrow I will see if I get the same results in my second world.

**Comment by Ladysarajane** [comment]
Odd but better, on my second world, the water poppet was quest 14 and the fire poppet was 13. Once I began each one, I was able to complete them with the finish poppet AND the items needed in my hand when I talked to Mary.  I received the taglock kits and the dye seed. I will try a new profile and world tomorrow to see if one of my files got messed up on download. Not sure why in my other world, I had to use quest 12 to start it.

**Comment by teagan75** [comment]
I did some tweaking with the poppet quests. Hopefully this is fixed in version 1.3

**Comment by Ladysarajane** [comment]
Anxious to test it. I had tried a new download  of Alpha 1.2 to make sure that the files were not borked and even started with a different poppet and still obtained the same result. Seems to go fine until I need to make the second one. Mary never gives me the chance to choose another one, nor to move on.

**Comment by Ladysarajane** [comment]
Okay new profile/files and world. Still was only to complete one poppet with Mary. I did complete the water poppet and I did receive the dye seeds this time, but she doesn't give me the option for the other two. I tried taking the ingredients to her, but she just says "Hello Ladysarajane"

**Comment by teagan75** [comment]
I think I found the issue. It is strange since I was able to complete this
on my recording instance. Unfortunately the newest update to custom npcs
broke cloning so each fix I make has to be a map reset

**Comment by teagan75** [comment]
I believe I have finally fixed this issue. I did a fresh play through to see what was actually happening so I think it will work now in version 1.4
