### ISSUE TITLE
1.5-alpha - Brew of Webs

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#30]
Madam Eva still only says "Hello, stranger." - do we need to restart after upgrading from 1.4 to 1.5?

**Comment by satanKami** [comment]
yes

**Comment by teagan75** [comment]
no dont start over. try using the clone of Madam Eva

**Comment by LindaJuffermans** [comment]
Will that also help with the other questlines like Victor's?

Just in case, I copied our farm/altar area (we're already at 8k power without demon hearts) and house with all the inventory to a new 1.5-alpha world 🙂 worst case we'll just be rushing through the questlines.

**Comment by teagan75** [comment]
I didn’t clone Vallaki npcs yet

**Comment by teagan75** [comment]
But an update to them shouldn’t require a map reset. Make sure to always keep your base in/near the town of Barovia during alpha testing. That way I can update regions without you having to restart.

**Comment by LindaJuffermans** [comment]
But how will your updated regions (in the template folder, I presume) make their way to our worlds?

Cloning Madam Eva got the Brew of Webs quest started.

**Comment by teagan75** [comment]
I will be able to overwrite the Vallaki region via MadHelp mod using the download button on the main menu screen.

**Comment by teagan75** [comment]
Only going to use MadHelp during testing

**Comment by LindaJuffermans** [comment]
Okay, cool. I noticed you added the mod (had to disable it on the server) but didn't know why 🙂

**Comment by teagan75** [comment]
Yeah client only. Haven’t worked on server files yet hehe
