### ISSUE TITLE
1.5-alpha - Morgantha's dialog (minor)

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#35]
After getting the disturbed cotten - oh, and thank you for making the nightmare world not as dark as it was on your videos - Morgantha explains about the dream catcher.

"You can now spin thread with the disturbed cotton and craft yourself a dream catcher to reduce the chances of a nightmare when sleeping. This effect will only happen IF you drink the brew of sleeping first. If you forget, you will have a nightmare"

Not sure what you meant to say by "IF you drink the brew of sleeping **first**"? The dream catcher is hanging above the bed, there is no order of things just drinking the brew - at least so I thought?

**Comment by teagan75** [comment]
As far as I know, once you place the dream catcher if you sleep normally in the bed you will have a nightmare.

**Comment by Ladysarajane** [comment]
Yeah, having the nightmare world a little lighter is so great! Thank you. I think that will help a lot of people unfamiliar with witchery.

**Comment by LindaJuffermans** [comment]
If you sleep in a bed with the dream catcher it will give the weakness effect for some time, it doesn't take you to the dream/nightmare world.

**Comment by teagan75** [comment]
I will double check and then change the dialogue

edit: ok weird. I thought the wiki always said you would get a nightmare regardless if you slept in the bed with the dream catcher. I will change the dialogue.

**Comment by teagan75** [comment]
fixed for version 1.6
