### ISSUE TITLE
Alpha 1.5  Kolayana Key (minor)

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#36]
When you use the key on the gate for the Kolayana House, the Key does not disappear like the other keys do. It stays in your inventory.

**Comment by teagan75** [comment]
yeah i never set it to disappear. Will have to fix that, but that will take
a map reset.

**Comment by Ladysarajane** [comment]
That's fine. I always test with map resets and new files.

**Comment by teagan75** [comment]
this will be fixed in the next update 1.6.4
