### ISSUE TITLE
Alpha 1.6.1  After Poppets

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#38]
Poppets now flow from one to the other now without difficulty. However, when done with the poppets, Mary will not advance to open Gertruda quest line. She just keeps repeating the poppet convo even though there is no more poppets to complete.  If I remember correctly she opened up the Gertruda quest line,  before which pointed me in the tavern direction for the quest for Ireena.  I did take each poppet to her after completing,  NPC log has nothing open in it and all three poppet quests completed in Better Questing.  There is no hint on what to do next. Also when I did the fire poppet, I had two wool of bats when crafting it and when I took out the completed poppet out of the crafting table, two wool of bats popped into my inventory. This happened both in fresh files of 1.6 and 1.6.1.

**Comment by teagan75** [comment]
I had the wool of bat return to me too so I have no idea what that is. Perhaps a mod bug. 

Because of the poppet quest issues, I had to gate it a bit. The poppet dialogue should stop after the altar quest. Gertrude will open after the altar quests. Also, Ireena should be open in the quest book at this point anyways. 

Hope this helps 😁

**Comment by Ladysarajane** [comment]
I know the tavern quest  opened up and what comes next, but with the gating of the poppets, Mary keeps up her dialog about poppets which might get some people to think that it is still not finished,  And they won't think to check better quests to move on.  Maybe add a small little quest with Mary before Getruda quest  like getting her a flower pot in exchange for magical fertilizer and when you complete it, she gives you the fertilizer and says thank you and people will know poppets are done with her and to move on in the quest book?

**Comment by teagan75** [comment]
The way the poppets are set up I can’t add another finishing quest but I may just add a finished dialogue 

Gertruda in the quest book is gated too so chances are players won’t get confused. It’s  more likely that you just remember it one way.

**Comment by Ladysarajane** [comment]
I am not sure how you write quests for the NPC's as I am not familiar with it that mod other than what I am learning here, but from what I have seen, adding a dialog might be difficult for it to come after all three poppets are done. (Not sure how the checks are done in the mod). I do remember the Getruda quest coming after the poppets and with Mary telling me to MOVE out it made me seem like the poppet quest was finished and I looked to the Better Questing Book to see what to do next. 
As it stands now to Me, I don't know if anyone else is replaying this to check it out, With Mary still repeating her dialog about poppets even though all three are done, it is feeling unfinished and if I was playing it for the first time, I might think there was still something undone about the poppets and less likely to look for the next quest. I know I am OCD linear type of person ;) and less likely to look for other quests unless everything before me was completed as far as it could be. 

I wish someone else would replay this to this point to get their take on it, to see if I am being too obsessive with it. I do LOVE that the poppet quest flows now. I did do it different ways by opening a couple at a time and they all completed without problems. People unfamiliar with questing shouldn't have a problem with completing the quests, unless they forget to take their items to Mary.

**Comment by teagan75** [comment]
Like we said I will try. Just afraid I will screw it up again lol

**Comment by Ladysarajane** [comment]
I can understand that. It works well now with all your work on it. I tried to break it in different ways with The poppets and they start and complete now without problems in different ways. Thank you for understanding my point of view on this. I wish I could give a suggestion on how to get the point across to new people playing this that quests are not linear and to try other quests if one is finished in thier quest book,  but doesn't move on in that line.

**Comment by teagan75** [comment]
Yeah. It will cause the same issue unfortunately. If the different poppets had different IDs I could do it but they all share IDs just different nbt data.

**Comment by Ladysarajane** [comment]
So do you want this issue closed since nothing can be done at this point?

**Comment by teagan75** [comment]
I will close it. Thanks for your feedback tho!
