### ISSUE TITLE
Add Suspend Server mod to server file

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#4]
![2017-12-06_11 45 15](https://user-images.githubusercontent.com/31929183/33671191-451c1244-daa7-11e7-9f3e-d59f473b3220.png)

This is always happening when we are outside (and they often come indoors with us too). Interestingly they don't harm us at all but they are annoying (especially when we're trying to harvest crops or break trees).

**Comment by teagan75** [comment]
Wow! I don’t have those issues when I record 😳 and you started over? Maybe try lowering the spawn rate again in the configs and then change to peaceful to get rid of the mobs and return to easy again. Idk when I test and stay outside I don’t have those swarms

**Comment by LindaJuffermans** [comment]
I reduced spawnlevel to 2; I'll try again later to see if that's sufficient or too low. Peaceful mode doesn't work; I suspect DifficultLife overwrites it. Creative mode with a zivicio sword worked well to thin the herd 🙂

**Comment by teagan75** [comment]
It’s not difficult life. I believe it has to do with Aggro Wolves and the dev not changing the tag to hostile instead of passive

**Comment by satanKami** [comment]
wow ive yet to get to that point...

**Comment by teagan75** [comment]
Now that I think about it. If you are running a server with this pack the difficult life globally increases with ticks. I will need to put suspended server in the file

**Comment by teagan75** [comment]
this is no longer needed as of a new update to Difficult Life
