### ISSUE TITLE
alpha 1.6.2 full report

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#40]
- i can warn the man from nikolai atttack
and i can join them in attacking the poor tiger(kitten)both quest
- tiger cant get out of cage
- the seal in church still block willemena you can move it 2 down or one to the left(the edge of the seal is on her)
- found empty second vistani camp near valaki
- krezk cant be found and the fountion has one nether brick missing
- cant be found rahadin the quest after ernst larnak
- wisteria wont active gadgets after broom quest
-  wisteria wont actove mutations after broom quest
- bella after finishing owl quest cat and toad wont be re-trigger so you cant finish them
- bella quest book parts of them is empty so you finish the owl quest for npc but not in the quest book
- coven #59 quest wont trigger morgana

welp night ^_^

**Comment by teagan75** [comment]
Sigh. I still have work to do lol but thank you. 

But Krezk and Rahadin weren’t in this update. I am getting closer. Working on the castle atm

**Comment by teagan75** [comment]
Also the Vistani camp will be finished along with Lady Watcher in Vallaki. Those plus Yan at the tower belong to an alternate path.

**Comment by satanKami** [comment]
lol you slowly finishing it bit by bit and ill do whatever you need to complete it...well except recording with modii

**Comment by teagan75** [comment]
Bella, Wisteria, and Morgantha should be fixed for 1.6.3 also Rahadin is in the castle if you start a new game.

- Nikolai, the cat, the seal in the church should be fixed for the next update (1.6.4)
