### ISSUE TITLE
Alpha 1.62 Owl Familiar Quest

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#41]
I wanna fly on a broom, so I decided to go for the owl familiar. Bella quest in Better question apparently has 10 dialogs although there is nothing written on some of them, I assume it is a check to take things to Bella. 
Problem number one. STupid zombie. Like you I could NOT for the life of me get a zombie to spawn so I could lead him into the mutating house. After 3 hours I gave up and gave myself a zombie spawn egg. Problem number two. After charging the attuned stone and taking it back to Bella along with the extremis mutandis she keeps talking about how to mutate the bats into the owls the actual ritual for it....but I have not received the bat spawn eggs to do it.  I have the mutating sprig and the cobweb, graspers and the other things in my inventory. What am I missing? How do I get her to give me the spawn eggs so I can use them? Oh, I do have a spawn wolf egg on me, I bought from the pet shop. 

I am taking a break, then I will use a backup to see if I can redo Bella's quest so I can see if I am missing anything.

**Comment by teagan75** [comment]
Ok so I changed alot for Bella's quests but didn't do any clean up :( with the next update you will be able to craft spawn eggs for bats, slime, etc. that are needed for quests. I will add the zombie one too.

the dialogues have been deleted and that is why the questbook shows empty tasks - just needs clean up

Going to try and get a quick update out today with these and other fixes.

**Comment by Ladysarajane** [comment]
Okay :) Looking forward to the update.

**Comment by teagan75** [comment]
fixed in update 1.6.3
