### ISSUE TITLE
witchey report 1.6.3 part 1

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#42]
too much in the new upload to do in one day...damm you worked hard teagan
- barrier still block willemina(look at images)
- tiget cant go throw the 2doors`
- kreckz wont be trigger
- wizard of wines has nothing to be fear no enemy
- you need to break the wine wizard's loe to get to the chest with the diamonds(too small)
![barrier](https://user-images.githubusercontent.com/34218558/35476973-5b167eb0-03c2-11e8-819e-f7d98c8f8252.png)

**Comment by teagan75** [comment]
Barrier and tiger are fixed for next release and still working on finishing the wizard of Wines

**Comment by satanKami** [comment]
ok then so unless i see other problem there wont be part 2..
thanks for your hard work teagan
