### ISSUE TITLE
full report part 2-party time

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#43]
- the people for hire...they wont get up so you can hire them but they wont help
- how to tame wingedmonkey
- the mutantions and how do i use the untamed monkey still optional even if you finish the line
- brambles quest wont be trigger
- the dup granede wont be finished since the only one who can finish it is teagan75
- speak to animals wont be trigger after replacing the dup grenade
- me and teagan chilling....looking at her duplication grenade so i cant finish that quest...
![wreawfwe](https://user-images.githubusercontent.com/34218558/35480388-86c41d6c-0415-11e8-9907-22ca992fac46.png)
- god bless us with an army of teagans!!
![grswfdeef](https://user-images.githubusercontent.com/34218558/35480389-87ffd72a-0415-11e8-8194-eeaba71f2ed6.png)

**Comment by teagan75** [comment]
- lazy people lol
- I forgot to add that info 
- Mutations might not be able to do anything about that because it will act like Mary did
- will go check the brambles. Probably forgot something 
- that’s a lot of teagans LMAO
- will check the animal charm quest

At least these aren’t old issues anymore - progress!

**Comment by teagan75** [comment]
Oh and that’s kinda cool that you can dup other players and use it 😁

**Comment by teagan75** [comment]
For next update:
- Brambles should work now
- changed the dup grenade to reflection of:null but not sure that will work. I have the quest set to ignore nbt data and damage, but I may need to rework the quest completely. Yay for Witchery not being quest friendly lol
- also first conversation about the winged monkey has how to tame it but I will add it to the quest description

**Comment by teagan75** [comment]
Mercenaries are fixed for next update as well.

**Comment by satanKami** [comment]
instant of making it null maybe make the quest about holding the mirror and the quarts sphere since they don't have any chanced... once the mirror get possessed by the demon it wont be chanced 

off topic: the castle was really hard maze but i found like 5 empty chests...maybe it something?
and i think 2 other npcs ...that vampire servant really scared me(but they don't auto attack you(when i told him to leave with me)

**Comment by teagan75** [comment]
I will change that quest using your suggestion.

I have been working hard on the castle this week. The castle is a maze of rooms and I get lost ALL the time lol. I am getting the hang of half the place now. I am slowly replacing out the empty chests with my loot chests. I am also slowing decorating and adding occupants to some rooms. It will be well worth exploring in the end I hope.

Glad the vampire spawn scared you and that it didn't auto fight. They are still pretty tough to defeat at this point. After the abbey quests (once I finish them) you should be ready to take them on as well as Strahd himself  :)

**Comment by teagan75** [comment]
I hope all this is fixed in update 1.7
