### ISSUE TITLE
Alpha 1.6.3 Dream World Question

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#45]
Okay I'm not sure here, but are villages suppose to spawn in the Dream World? I found a pretty large one and a couple of the villagers were witchery watchers. The had bows. Not complaining, I got potatoes and carrots to boost my altar power. It had a blacksmith and I got an iron helm. Just didn't think villages should spawn.

**Comment by teagan75** [comment]
Well it’s suppose to be a copy of the overworld. So I guess that is possible 😁 lucky you! There is probably a village in the same spot in the overworld unless I wiped it out lol

**Comment by Ladysarajane** [comment]
Yeah, when I get back to the overworld I am going to check it out and report back.  :)

**Comment by Ladysarajane** [comment]
The village is not there in the overworld. The land terrain is different too. Does the realistic terrain not affect the spirit world?

**Comment by teagan75** [comment]
It might not. And the only Village I have seen in the overworld is west of Vallaki.

**Comment by Ladysarajane** [comment]
That is where the coordinates took me. Near bamboo trees and I could see a coven witch hut in the distance. In the spirit world that was all mountainous. With the village scattered throughout.

**Comment by teagan75** [comment]
So I think it’s safe to say realistic terrain gen does not affect the spirit world.

**Comment by Ladysarajane** [comment]
Yep and since this isn't a bug....just interesting info I will close this issue. :)
