### ISSUE TITLE
Alpha 1.6.3 Zombie Flesh

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#46]
Not sure if this is a bug or just a issue, but to make zombie eggs you need zombie flesh, but even though my world is in normal, the only mobs spawing for me are the amnesia mobs, I did have plenty of wolves when first spawing in the world, but now I can't even find them. My difficulty is slightly above medium. 

Spawing of normal mods seem to decrease as amnesia level difficulty increases? Could it be that more amnesia mobs spawn, thereby  bringing down the normal mob spawns to keep mob spawning caps?

 To solve the zombie egg problem, I did use the vegan option. Thank you for putting that in. :) I used it in the spirit world to find jute to make string. Maybe add a blurb in the better quest somewhere to look for alternatives in recipes.

**Comment by teagan75** [comment]
I can't turn the spawn rate of amnesia mobs, but that mod isn't affecting
other spawns. Difficult Life shouldn't be either, and I plan to include
Peaceful Surface mod to the pack so mobs only spawn in light level 0. I
think that will help with excessive mob spawning in the Death House and
Castle Ravenloft.

As far as the Vegan Option, I though about putting some of the devices in
Vallaki for players to use and experiment with. Glad you saw the option!
That was the whole point of me putting it in :)

**Comment by Ladysarajane** [comment]
If Peaceful Surface mod is installed will that affect the spawn rate of the aggresso wolves? We need them for tongue of dog, and I don't see a recipe to make them.  In watching my Journey map spawns, the mob spawning in the death house seems to be amnesia mobs....I don't see zombies or skeles on the map. Those seem to spawn early in the game and seems to decrease as my difficulty goes up.  I do  seem to be hit by those crazy brutes and servants a lot now with the increase difficulty. Just walking through the woods at the bonegrinders I got mobbed by 4 at the same time. Needless to say, I didn't survive. I have finished the demon quest to get the heart and my difficulty level is now at hard. Could be I had to explore in the spirit world to find the jute for string and to find the stupid diamonds That could be why my level is higher. 
Hee Hee, I used the trapped poppies to slow down the demon. Slowed him for a few hits and so I could trade easier. Just need to avoid them myself. Only had one hole blown in the ground LOL

I haven't heard from anyone else about the spawning level, so I don't know if my case is isolated or not. Peaceful mobs are plentiful. 

I needed to change my altar around to make the 15x15 infernal circle. Now my altar power has dropped drastically. I need to redo my garden so the altar can reach it better and replace plants destroyed by demon. It will be awhile till I bind my owl.

**Comment by teagan75** [comment]
I am currently testing peaceful surface. Will see what happens in my recording instance. So far in the dev instance it has lowered amounts of mobs spawning but not eliminated them

**Comment by teagan75** [comment]
Oh and I have seen more vanilla mobs than amnesia ones in testing now

**Comment by Ladysarajane** [comment]
That is good for more vanilla mobs.

**Comment by satanKami** [comment]
i have tons of zombies...and some that weird mobs

**Comment by Ladysarajane** [comment]
For 1.7.2 I am still experiencing decreased vanilla mob spawns. I get wolf spawns but not in Town of Barovia. I expected to to see vanilla spawns in empty houses but there is none. When I am out in the world, I see some underground spawns but not not many and if I am in the dark forest, there is none I see on the map. I have not messed with any difficult settings at any time and these are fresh files and world. My difficulty right now is hard and with Ents and peaceful mobs it is harder. Agressive wolves are harder, but I have to move away from towns to get them. I am close to the demon summoning again. I get plenty of brutes and grunt spawns in the world. Just not sure why vanilla mobs are stubborn. Glad I can make zombie eggs. 
I love the improved Vallaki and the soul stones instead of cages. The altar quest line is awesome. I learned a lot from it. Teagan you are doing great work with this. The towns are awesome in the builds and Npc's interactions. Quests are very informative for the ones you have completed. Storyline is great. Thanks for letting us test this!

**Comment by Ladysarajane** [comment]
Ugg....Soon after writing this, my world crash after talking to Victor and I cannot get NEI to recover. Since I am unfamiliar with a lot of the recipes, I cannot continue with this instance. (Even after a complete reboot of the instance)  I will have to restart with brand new files.  I am not on a server, but using twitch. I will try new files and put this world back in to see if my old files are corrupt somehow from twitch. 
Kinda sad cause I really had a great garden and altar power and it is going to be a while till I get there again.

**Comment by teagan75** [comment]
Can you replace your world with one in the backup file? Also if you have a
crash report that would help.

**Comment by Ladysarajane** [comment]
I have the world running again. I think the files were corrupt with the first instance. I had some bad chunks in the spirit world. I put my world in a new set of files and everything is back although I have not gone to the spirit world to check those chunks. I think I deleted the crash report when I deleted that instance. I will check to see if twitch saves them separately. I honestly can't remember. Been a long week. Was almost robbed via paypal of 1000.00 when someone got into my account and tried to send a wire transfer to themselves. I got it back though. Thank Goodness for text alerts from my bank. I was able to stop it before It was sent from my bank, but I had to jump through hoops...file police report etc, before my bank would give it back to me.

**Comment by teagan75** [comment]
Oh man that sucks. Glad it resolved tho. I hate those loops but I guess there is a reason for it. Hope the rest of the week is better 😊

**Comment by Ladysarajane** [comment]
Okay...I thought the profile was deleted...still there. Let me try to attach the crash report.
[crash-2018-02-22_17.22.01-server.txt](https://github.com/teagan75/Witchery/files/1749972/crash-2018-02-22_17.22.01-server.txt)

I guess I will find out if I attached this right. Yeah, it was close though. If I didn't get texts from my bank, I might not of known right away and it would have been harder. Things are better, if the rain would stop. :)

**Comment by teagan75** [comment]
So I have been getting this crash randomly (usually after teleporting) for two weeks. Coincidentally Mojang shut down their old skin servers at the same time. I am wondering if Witchery accessed those servers. If that is the case, there is no fix. The crash itself is not helpful at all ☹️ I have always been able to relog after the crash. The crash points to the player being the issue not an item or block

**Comment by teagan75** [comment]
I forgot to mention that I disabled skin overlays from etfuturum mod. If skins are the issue, hopefully that will help. Idk worth trying. The new config will be with the new update. I hope to release that today sometime.

**Comment by Ladysarajane** [comment]
Okay thanks for the info...you know it is right about teleporting....I forgot I had teleported from Victor to home (teleporting has been my only cheat while testing).  The only skin I have is older but I only currently have iron armor added to it. It is currently working with a new set of files and that is what is important. I will await the new update.

**Comment by Ladysarajane** [comment]
I'm not sure but I think some of these crashes are caused by leads. Every time I teleported to my home, the lead on my owl was broken and all my crashes related to only teleporting home. I made the chunk loader for in my house and now the lead is never broken nor have I crashed. I still think a file was borked on my one set of files.

Now this could be related to a borked save, but when I went to get the demon heart, I never got the heart after defeating the demon. Summoned one 3 times. Luckily the third time I had the right items to trade for a heart. The first time it could have burned in the resulting fire, but not the next two times. As I said it may be a glitch in my save. 
Not sure if anyone else has had that problem.

**Comment by teagan75** [comment]
If the owl is in your base attached to a lead, it dropping is just loading
and unloading chunks. The crash says specifically that it is the player
that is ticking. The only way I have made it better for a while is when I
put everything on me in a chest, logged off and cleared all my player data
(not quest data). Then I could tp around again.

**Comment by Ladysarajane** [comment]
What ever it is for me, it is in all the test worlds old and new with that instance. The launcher keeps complaining about missing null pointer exception. Here is the latest log when I was loading up the instance
[latest.log](https://github.com/teagan75/Witchery/files/1753915/latest.log) I think teleporting at that time was incidental and not the cause. I cannot read logs that well, but it does seem that Vanity Armor is listed. Is the brew bag considered Vanity Armor? I know I had that in my inventory, but nothing was in it. 

Whoops not the cause, my log on my working instance is giving a similar log with the launcher. Not sure why one instance is working and another one isn't with the same worlds. 

I think you said you were changing configs, so hopefully that will help.

**Comment by teagan75** [comment]
Difficult Life always spams the vanity armor stuff in the logs. It’s aggravating. I may see if I can disable that too since it’s not really necessary.

**Comment by teagan75** [comment]
Ok, none of my config changes solved the crashing. I went onto the Minecraft website and changed my skin to the Alex model and I haven't crashed yet.

**Comment by Ladysarajane** [comment]
I will try that too and see if that helps.  I was watching some videos. Did you know hobgoblins are suppose to have breeding capabilities similar to villagers with doors but slower? Also they shouldn't be able to break wood planks. So to keep them in an area, surround them with wood. Maybe give a koboldite axe as an award somewhere to help a hobgoblin perform better?

**Comment by satanKami** [comment]
lol good luck ive been trying to help teagan improve her workspace with wood... but nooo... its to close to lava even if she disable fire spreading...

**Comment by teagan75** [comment]
HA HA SatanKami. I just don’t want to bother upgrading 😝 but yes my issue with wood planks is too close to lava and it will set on fire and kill my hobgoblin. The slab on the bottom half is working well at least. I also did know that hobgoblins breed 😁

**Comment by teagan75** [comment]
The koboldite ax is a reward for completing the pentagram quest but not before hehe

**Comment by satanKami** [comment]
just pointing that ive show an image how to use piston to make a pillar with 2 slabs with a slab space in the middle so the hobgoblin cant enter the cobble pillar since the first wooden slab is on the ground

and by using storage controler with one of the draws to be full of cobble with void ~that image
and the hobgoblin did burn in the end (e42?) -_-

**Comment by satanKami** [comment]
and yes im in a bratty mode today
