### ISSUE TITLE
Alpha 1.6.4

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#47]
Uh, oh....I think you uploaded the wrong files to Twitch. I installed 1.6.4 as a new profile and when I started a brand new world, I started in creative and with my inventory full of stuff  such as the NPC wand and chests, doors etc, and I started in a room with cultists and a circle of magic. I think I was the Watcher house.

**Comment by teagan75** [comment]
Ah yeah I forgot to clean the level.dat whoops lol will try and fix that ASAP

**Comment by Ladysarajane** [comment]
Okay, looking forward to starting it.

**Comment by teagan75** [comment]
Update is live
