### ISSUE TITLE
Question on  1.7.1 beginning

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#48]
Downloaded new files and started a world. Are you suppose to be spawning at night now? In two test worlds, I spawned at nighttime. Other than that, It starts normally.

**Comment by teagan75** [comment]
Yeah that shouldn’t be happening either. But that’s easier to fix. This is what I get for trying to update with JJ around lol

**Comment by teagan75** [comment]
This will be fixed next update. For now just run command /time set day

**Comment by satanKami** [comment]
so this is why you were flying on that werewolf cave...

**Comment by Ladysarajane** [comment]
Issue solved with 1.7.2
