### ISSUE TITLE
Alpha 1.7.1 Wolves Question

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#49]
How much health should those aggressive wolves have in the beginning? As I was going to Mary's a wolf pack of three attacked me, and they each had health of 250. I don't remember them being so "healthful" at the beginning.

**Comment by teagan75** [comment]
What does the Difficult Life meter say?

**Comment by Ladysarajane** [comment]
Very Easy. I just started the game.

**Comment by Ladysarajane** [comment]
I logged out and logged back in and I was going to try to find some wolves again, and now I can't find a one and the death house is a solid red with non vanilla mobs.  I am dumping the profile and restarting with fresh files again. Odd cause other than having to sleep in the tent when spawning in, and meeting those overpowered wolves, Regular mods had been spawning  and the death house wasn't that bad. Now it seems regular mobs have disappeared, no wolves and the death house a nightmare.

**Comment by teagan75** [comment]
I think it must be random

**Comment by teagan75** [comment]
You should still be on peaceful during the death house unless you logged off before doing so

**Comment by Ladysarajane** [comment]
Okay that makes sense, I was unlucky with the wolves again when spawning in. First time, I had logged out and back in after I noticed the death house. I did a fresh install again and I saw a couple of wolves, but they were not that bad, but I don't think it is peaceful when going in the first time. If It should be peaceful until you log out and back in, I had mandrakes go after me at night and ents come after me and I had not logged out yet. The only thing I do when making a world is to change the setting to allow cheats. Not sure if that could be could be altering difficulty settings?  Also had a baddy spawn in Mary's house somewhere. He is noisy so I moved out already...LOL

I will make another world tomorrow and see what happens.

**Comment by Ladysarajane** [comment]
Okay, let me clarify somethings here....Question time! :)
If it is suppose to be peaceful, which mobs is it suppose to affect? The Amnesia mobs or the vanilla ones? I am assuming just the Amnesia mobs. 

What I have found is if I turn on cheats, (etc to give my self things while testing such as NPC wand  and to teleport in Journey map, I have amnesia mobs in plenty and very, very  little vanilla mobs. 
If I turn off cheats to create the world,  It seems that there are no amnesia mobs to begin with and vanilla mobs are present. Wolves where there with variable HP's but they were easier to deal with. It seems turning on cheats affects difficulty levels. Are the wolves vanilla with a mod or considered a amnesia mod? Sorry if I seem to be asking so many questions, just wanna figure out how it is suppose to work. 

Oh, crazy request but is It possible to reduce the need in the quest to one wolfbane seed? I spend FOREVER mowing for 2 seeds. It is hard enough to get one.

**Comment by teagan75** [comment]
The wolf mod is not part of amnesia. Cheats are enabled by default on the map so maybe enabling them again does something weird? Idk and I thought I already changed the wolfsbane seeds. Guess I need to check that.

**Comment by Ladysarajane** [comment]
Okay, I will check that out and see if I can "cheat" without enabling it...LOL
I will make an issue to remind you about the wolfsbane seeds.

**Comment by Ladysarajane** [comment]
After starting a new world and "not" enabling cheats it seems to be better. Only one encounter with wolves but I do see them spawning on the map. Still see lots of mobs in death house, but I think they are amnesia mobs. Just plain red dots on map. Mandrakes spawning still, but decreased. Ents, spawn, but again  decreased.  Heard the sound like 5 times, but only one actually spawned. So, in my opinion it is not peaceful, but manageable at the beginning. And I have not logged out since starting. Trying to get to the death house to see how it actually is.

**Comment by teagan75** [comment]
May have to think up some vanilla ways to change game mode temp to peaceful especially Death House. The hidden quest w/ command doesn’t seem to be triggering properly at the beginning

**Comment by teagan75** [comment]
Yeah the more I think about it even if the quest triggers, people get to the Death House at different points so a trigger right inside the house with small range would be good and then it triggers easy mode on way out

**Comment by teagan75** [comment]
Ok I implemented it into the map for next update. Should trigger after the death house quest and easy should trigger on way out

**Comment by Ladysarajane** [comment]
Okay...sounds good. Looking forward to the next update. All of the quests up till then and keys and other little issues seem to be resolved. And with me tackling the death house, I had to fight like 15 brutes. Many, Many deaths....LOL

**Comment by teagan75** [comment]
They are tough for sure

**Comment by teagan75** [comment]
Death House peaceful mode should be in update 1.7.2
