### ISSUE TITLE
1.2-alpha - Difficulty "I See You"

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#5]
I updated the pack yesterday and we restarted the map/quests. My friend spent about 4 hours yesterday; today when I joined the game the difficulty level was "Very Hard" and by now it has progressed to "I See You" - we've not even started the Madam Eve questlines yet... Even bats are around level 150.

Maybe it's because the server was kept running?

**Comment by LindaJuffermans** [comment]
It just increased to "I'm Coming For You"

**Comment by teagan75** [comment]
Crap I forgot to delete that. Sigh it’s separate from the level.dat

**Comment by LindaJuffermans** [comment]
Anything I can fix myself?

**Comment by teagan75** [comment]
In the world file there is difficult life data you can erase. It’s just strange because I only updated cnpc quests and region files not the rest  so it shouldn’t have changed anything

**Comment by LindaJuffermans** [comment]
It's back to very easy, tnx. I checked but the template folder (which I copied on the server to create "world") doesn't contain the file.

**Comment by teagan75** [comment]
Which is why I am confused how it set it so high
