### ISSUE TITLE
Alpha 1.7.1 Wolfsbane Seeds

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#50]
Looking for two wolfsbane seeds on the map is frustrating.  Since we don't need wolfsbane right away, Maybe reduce it to one for the quest and people can "grow it" in their garden to get more.

**Comment by satanKami** [comment]
isnt it one? i was sure....well you know modpack does need to be hard on something...and being witch hunter is hard...

**Comment by teagan75** [comment]
Fixed in update 1.7.2
