### ISSUE TITLE
witchery 1.7.1 full report 

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#51]
- what lurking around and spying eyes are the same but lurking wont be triggered
- stud invite quest the trigger is behind the place you geet teleported
- after killing stade (throne room lapis and dia)and go throw the door the painting on the fireplace is missing
- who is kaiuse?
- ezmerald wont talk to me(and the castle quest is locked till she will talk to you)
- barseleen suppost to say "hellow stanger"?
- painting near chest treasure 1 is missing
- giant spider wont attack but say hi stanger
- i cant take garturda with me
- escher can't see his quest
- above servent that you first meet the upstairs there is a missing painting
- prison bed's are all messed up
- grizzleut is saying hello stanger
- the tower in the mirror room there is hidden elevanter that cant be used
- i helped emil and he attacked me....
- in the graveyard the place belong to me...there is a corpse that say "hi stranger"p.s cant you rig the skin to be based @p- so it will be the players skin?
- vision the one who is suppost to give you a bone of himself isn't giving you one
- sergei's gravestone ...stard say hello stanger....
- in stard gravebuilding one wife is missing a sign
side note: so many wifes...did he once tried to be with a male?
- mad mage location too far away from cave and the quest he give wont be triggered 
- vampire bat wont wander or fly...
- werewolf will attack you even if you bring annebell so is the vistani camp(the other)
- werewolf den....amm teagan the location in the book...it's well i need to fly to get to it...can we do it more into their cave location?
- abby is empty
- àrgynvostholt is empty
- amber temple is empty...god of secrets is with no secrets
- tsolemka pass the bloody straw wont get lit..maybe cause his too high...joke(or i or the statue isnt design right...need to be re-checked)
- the horned huntman staff is rare drop...spawned like 3 to get one...
- baba yaga spawner spawn to manny!!i got like 11
- none of the druids talk to me and tharion and calllita say hi stanger
- urwin wont take his wine...
- lady fiona watcher just hi stanger...and yes ive used 5 tnts to get into there...
- stella...the priest wont help her!(its father btw)
-epodyno pet shop...he's a witch! he made his pets talk!
 p.s i do commend in stad castle using a mob and then removing it(just for decoration)
it called biome wand mod(found it while thinking how to make the bee modpack that can make small pokets of biomes so you can make stud's castle be a mix of biomes and our map will go crazy showing us diffrent biomes and then remove the mod since we dont need it....)

as you can see the barrier wont close the opening if you want it to make it one block higher
![fadfwdfr](https://user-images.githubusercontent.com/34218558/36051469-efde916a-0df2-11e8-870a-8781c66ef224.png)

**Comment by teagan75** [comment]
- What's Lurking Around is triggered by completing Willemina's quests. Just another way to get an invite. If you get the dinner invite one way, you won't get another one.
- If you are talking about the Invite quest in the Castle Ravenloft chapter, it triggers once you teleport to the castle and is intended. Its only a location quest.
- Forgot to add the file for custom paintings
- "who is kaiuse?" I have no clue? where?
- Ezmerelda will not talk to you in the castle or in her tower? If you tell on Victor to the Baron, she doesn't open up. Players will have a second chance at Argynvostholt once I am finished with it.
- will change all the creatures to stop talking lol and technically barseleen is a familiar so he could talk lol
- will have to double check spider
- I still need to add in the castle quests to the book. wanted to get the map done first.
- did you try to use the elevator by jumping on the block? there should be openings at the bottom and top, no where else
- There is no way I know of to rig the skin to be a reflection of the player but i can try to change the model to the witchery reflection and see what happens
- the time setting for the pack, same sex marriage would be prohibited - no heir possible. Princesses were also given as trophies and gifts for treaties. The wives are before he became the vampire and he turned them to spawn. The others in crypts either begged to be wives or they looked like his obsession, Tatyana (Ireena) - spoilers. After becoming a vampire, nothing mattered anymore. He could have consorts and Escher is one of them.
- vampire bat has limitations that don't let him fly so he just sits there
- This one confuses me "werewolf will attack you even if you bring annebell so is the vistani camp(the other)" the werewolves and vistani have nothing to do with each other. Annabell gets returned to the vistani camp outside Vallaki. 
- The werewolves shouldn't attack you unless you decide to go after their leader. I will double check all their settings.
- Emil will attack if you have not gotten the quest from the werewolf den. He should respawn so you have another chance. He wants to kill you so he gets back in the good graces of Strahd lol
- the tp point i wrote down from my journeymap forgetting I was flying lol
- the tsolenka pass strawman, the bloody wicker needs to be placed in the same orientation as all the haybales too, which isnt easy, then lit. Tested it again.
- yep the bosses drops are rare but they are op items usually. 
- removed Baba Yaga spawner for next update. Going to tell players how to spawn her legit, but only those who choose the black magic path with Fiona Watcher.
- druids are not finished, amber temple, argyn, and abbey are still on to do list
- forgot to remind urwin he wanted wine :P
- Lady Fiona will only trigger after you get her invite to dinner, the door as well but need to see if that is the case with the second option to get her invite
- yep forgot to add stella quest to priest
- "as you can see the barrier wont close the opening if you want it to make it one block higher" so picky lol

**Comment by teagan75** [comment]
- spider wasn't on aggressive - fixed for next update
- gertruda quest fixed for next update
- "the tower in the mirror room there is hidden elevanter that cant be used" I know what you are talking about. tried something and forgot to remove it
- reflection model does not work
- fixed the vision in the crypt giving the bone
- mad mage fixed for next update
- Fiona should work as well as the doors (for both ways to get an invite) after next update
- Stella's quest should be fixed next update
- I brought the circle under the church up one block, hopefully that will work

**Comment by satanKami** [comment]
after what you said about choices i realized that
 i didnt too the paths that were so i chose the baron path...
(btw if i knew what path will make me an enemy of that group .i wont call sudden attacks as issue)


- encheter plus mod is now gone
- spectral familir you also need arthana(you will get it back)
- once you get teleported to Castle Ravenloft the location quest wont be trigger since it's further away then the location you get teleported(the trigger isnt close to the teleportation) 
- i helped victor with the baroness so ezmerelda suppose to help me(dialog was empty)
- the werewolf will attack me no matter what i did...so as the vallaki vistani camp will auto attack me and her father doesnt have dialog(that the confusing line i said that they both attack me and vistani even if i hold the kidnap child)
- about emil you may want to make his attack line make more sense...cause it was weird that he sudden attacked me
- tsolenka pass was tested and yes the hay need to be like wood one side- my mistake >_<
- yeah im super picky tester  ^_^
- "on your own "there wont be trigger in the blue inn-no location block
- side with fiona wont be triggered even if i did willima
- book club's poppets wont be triggered after it's completion
- izek strazni wont be killed by vampire dolls!ànd ive tried both ways
- cant speak with zuleika her dialog is blocked
- while talking to zuleika she will attack me before i even choose what to say...

**Comment by satanKami** [comment]
like i said in the comment this is how i make my dust with piston pushing the cobble down and the slabs blocking the hob goblin from killing himself and another one to collect all what he mined
and with void added to the cobble drawer i dont have cobble problems (i hid the controller and cobble drawer so it;s just drawer with dust infront of me
![d](https://user-images.githubusercontent.com/34218558/36073344-ade87b86-0f37-11e8-881f-a9a31dc6fcb8.png)

**Comment by teagan75** [comment]
- i removed enchanting plus because I decided on a different way to give enchants
- for the spectral familiar if you mean I need the arthana as part of the items for the quest completion, customnpcs limits you to three items to gather in quests. I added a full list in the questbook tho
- I don't know why the Invitation from Strahd won't complete in your questbook. It opens up when you have completed Spying Eyes. I double checked the tp coords in book and with the guy in the carriage, and they match.
- help victor with baronness > talk to Rictavio > Ezmerelda in the tower
- stupid faction issues, will try again with the werewolves and vistani
- I can have emil scream "For Strahd!" as he attacks LOL anyways did you kill emil? you should have regained faction points for the werewolves to make them neutral again.
- location block fixed for inn
- fiona should be fixed for next update
- When I tested he was killed very slowly with voodoo doll. Are you saying specifically the vampiric one doesn't work? He doesn't regain hitpoints.
- fixed Zuleika's dialog for next update
- zuleika is probably same faction issue

**Comment by satanKami** [comment]
- "help victor with baronness > talk to Rictavio > Ezmerelda" in the tower i did and after that when i was in the castle she wont talk to me
-  i will try using voodoo on him to see if it's just vampiric puppet that doesn't work on him
i drowned burn myself and got it by guards...only when i got hit the puppet got used but didn't effect him

**Comment by teagan75** [comment]
Ezmerelda doesn’t have much of any conversation attached to her in the castle. Not sure where I want to go with that. Was thinking she might lead you to the witches in the castle. But she isn’t complete.

**Comment by satanKami** [comment]
- polynesia just a note you need to click her before you use the charm on cecil
- i think you should add seer stone near the start of gadget not in the end...cause it helps with spells

**Comment by teagan75** [comment]
- hmmm it adds a tag. I thought i tested that.
- I think I will keep the seer stone where it is. I haven’t asked you to do spells that require the coven yet. Helping players build up their coven atm
- also how did the grenade quest go? I never changed it from “null” - slipped my mind

**Comment by teagan75** [comment]
- Vistani should be good now for next update. I had the faction increase on wrong quest. I will probably put out an update late next week after everyone has had a chance to report. 

Thank you for all the detailed help 😁

**Comment by teagan75** [comment]
Ok vampiric poppet does work but I need to be more specific about how it works

**Comment by teagan75** [comment]
You craft the poppet with your taglock in the top left slot, Izek's in the top middle and the poppet in the top right (works going down as well). Only physical damage works, so mob or player damage not passive drowning and burning. Those work with the voodoo one supposedly.

**Comment by satanKami** [comment]
" also how did the grenade quest go? I never changed it from “null” - slipped my mind"
- i never notice it ...yeah worked puuurfectly null workes! 
+Thank you for all the detailed help 😁+
- well i am your beta tester...and if you need me to beta other like "fate of gods"or something like that...
i will gladly help out(and you told me how to make modpack so i can tortu.... i mean  teach just teach modii and other stuff...and what are you think about biome wand on the castle as decoration trick?

- just tested the poppet i dont get damage from npcs but mobs can do it and since his health so high i need 2 poppets(edit:his health for me was 153 and it droped to 70 and then he didnt drop anymore...)
(all my testes were with passive death and npc attacked-that none of them will trigger the popper

**Comment by teagan75** [comment]
Hopefully most of this is fixed in update 1.7.2
