### ISSUE TITLE
Beginning World of I.7.2

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#52]
Better Questing  was left in edit mode in the beginning.  First location quest wasn't completing and I realized it still was in edit mode.

**Comment by teagan75** [comment]
I know. Silly me forgot and didn’t remember until I published it lol

**Comment by satanKami** [comment]
lol i was about to report that for some reason the location wont be trigger...

**Comment by Ladysarajane** [comment]
This seems to be fixed in the update. I had no problems when starting
