### ISSUE TITLE
Alpha 1.7.2 Kolayana Gate

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#53]
The gate is unlocked (still closed, but unlocked) in the beginning.  (Double checked this with another new world)  I am up to starting to go into the death house. Everything seems to fixed up to that point. Like the dialog changes with Mary and when to move into another house. Poppets still seem good. Having fun testing again :)

**Comment by teagan75** [comment]
Weird the gate was unlocked. Haven’t touched it hehe. Glad you are having fun again! Lots of new stuff added!

**Comment by Ladysarajane** [comment]
Yeah, the gate and key worked fine since you had fixed it. The first time I used the key to "unlock" the gate this version I wound up locking it with the key and I thought "what??".  So I unlocked it  with the key and the key disappeared. Tried a new world and walking into the town, I tried the gate (I had no key) and the gate opened and wasn't locked. Weird that it worked in version 1.7.1 and not this one. Luckily it is minor issue.

**Comment by Ladysarajane** [comment]
This is still unlocked with the new fix update.

**Comment by teagan75** [comment]
Ok I may have forgotten about it. It’s been a while since I updated

**Comment by Ladysarajane** [comment]
That is okay. I saw there was an update out and I wanted to check it out, to see if these were fixed.

**Comment by teagan75** [comment]
I snuck in an update cause Christa and Haliee are starting the pack as a series

**Comment by Ladysarajane** [comment]
Ah good. They are finished up with the Simple Life2. I  am looking forward to watching the series.  Are you still recording the series too?

**Comment by teagan75** [comment]
fixed in 1.8
