### ISSUE TITLE
Witch Hunters Clothes (minor discrepancy)

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#56]
Ezmeralda wants you to make witch hunter clothes. There is a discrepancy with the NPC quest log and the Better Questing Book. The NPC quest log only wants the Trousers, Boots and Cape and doesn't mention the Hat. The Better Questing Book wants the whole set.

**Comment by satanKami** [comment]
the npc mod can ask you up to 3 items so she can only put 3 this is why in the book she asked for all 4 so it will force the player to make the full armor set

**Comment by teagan75** [comment]
As satanKami said, that is just a limitation of custom npcs
