### ISSUE TITLE
1.7.2 alfa: Mad Mary stuck?

### ISSUE THREAD

**Issue by 05nataku** [teagan75/Witchery#57]
After making all 3 poppets Mary doesn't go and talk to me about Gertrude? Is something wrong with my save or is she a bit broken here? She is supposed to tell me where to find the castle thing to go save Gertrude, but she just keeps repeating the poppet dialogue without the options for the 3 poppets even though I made them. Help please?

**Comment by satanKami** [comment]
if you look at the book it will show you another mission to do
since the 3 puppets are a loop she will stay that way till you need her again

**Comment by Ladysarajane** [comment]
Since Teagan had to "gate" the poppet quests to make them work correctly, the next conversation with Mary will happen after some of the other quests are done. Another quest has opened in your quest book that will eventually lead you back to Mary. A lot of these quests are non-linear

**Comment by 05nataku** [comment]
Thanks guys! :3

**Comment by teagan75** [comment]
Wow! You guys are on top of this! And yes everything they said is correct. Limitations of custom npcs. Follow the better questing book. If it’s open, you can do it. If it isn’t then there is something else to do. Usually if you hover over the quest in the book, it will tell you what you need to complete 😁
