### ISSUE TITLE
Chunk Loading 1.7.2 fix

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#59]
Teagan I know it has been discussed about the teleporting issue. Just wanted to have a place for input. I have only had that issue once with this new fix. However I am having chunk loading issues. If I am walking (not teleporting) and go to a different chunk (sometimes happens when I leave the Vistani camp) I run into a chunk loading issue. I have been in the chunk before, it just doesn't want to load. Only way to get it to load is to log out and log back in. I am NOT using chicken chunk loader. I did not have the chunk loading issue on other builds. Just the teleportation issue. I am using the Alex skin now.  My feeling is that there may not be a fix for this. especially since this is an older version of Minecraft. At least with my chunk loading issue there is a "workaround". I am just concerned that when I open more areas, I might run the problem more often and I might try to teleport into an area that won't load. 
In your world, do you have a problem teleporting into an area where the chicken chunk loader is?

**Comment by teagan75** [comment]
Yes. Try disabling or deleting Chicken Chunks. I have a suspicion it might be that mod. Especially if you have one running. The next update I am removing it.

Edit: Just saw that you said you aren’t using one. The mod still might be messing with calculations tho.

**Comment by Ladysarajane** [comment]
I will keep it from loading and see if that helps the chunk loading issue.

**Comment by teagan75** [comment]
Ok. I know about when the crashes started. I should look through my change logs to see what changes and if that is when I added the mod. Or maybe a different mod that is conflicting with chicken chunks

**Comment by Ladysarajane** [comment]
Since, I removed chicken chunks, I haven't had those loading chunk errors.

**Comment by teagan75** [comment]
Me neither 😁👍

**Comment by teagan75** [comment]
pretty sure removing the mod with update 1.8 solves this issue
