### ISSUE TITLE
1.2-alpha - Dead House hidden door

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#6]
When we entered the large room on the ground foor of the Dead House, the trapdoor to the basement was already opened. We had discovered the dead adventurist and the parents long before we had reached the attic. Perhaps you saved the world while it was open?

**Comment by teagan75** [comment]
Yep I think so. I will make sure it is closed.

**Comment by teagan75** [comment]
Fixed in version 1.3
