### ISSUE TITLE
Some things I ran into?

### ISSUE THREAD

**Issue by 05nataku** [teagan75/Witchery#60]
1. The gate to Ireen's house is open before I even have the key? Not sure if it is supposed to be as her brother does give you a key when he asks you to convince her to move.
2. The npc quests sometimes do not complete? For example I had to make the poppet 5 times before Mad Mary finally realized the quest was complete. ( IMO Mary needs glasses lol) The quest with the guy watching you also suffered from this problem in that I had to talk to him several times before it registered I talked to him and I got my letter. Also had to travel to the castle several times before custom npc's quest thingy realized that I did it)
3. The abbey has 2 doors labeled room 10 and they do not connect to the same room. (Monks also need glasses it seems jk)
4. Tiger side quest might need a hint-hint kill the thing hint-hint either that or I'm just super oblivious oblivious lol Stood at the cart staring for nearly 20 minutes at the tiger wondering what I was supposed to do to get tiger before I realized maybe I should attack back? XD
5. I  broke out the chimney to make room for all my chests of stuff (Looted the town chests before starting the story proper) and when the wool of bat quest came up no bats spawned. Might wanna make chimney unbreakable or something?(I could just pickaxe the blocks out of the way btw) 
6. I crash to desktop when I try and teleport with the journeymaps mod? It's weird because it only started doing this today. Thought maybe someone else playing knows what I broke this time lol

The last happened during the stream so I sat there all 'Welp I broked it....Teagan! I brokeded the modpack!' and then had to spawn the bats in myself.

**Comment by teagan75** [comment]
1. That will be fixed in next update. 
2. Cnpc has an issue with desync and there really isn’t a solution. Sometimes talking to the npc again triggers it. 
3. I will look into the doors at the abbey 😁
4. That tiger never wants to come out lol
5. There are other houses with bat spawners
6. Take out chicken chunks. I narrowed those random crashes to that mod.

**Comment by Ladysarajane** [comment]
O5nataku, as to number 2, make sure you look at the NPC quest log, ( independent ) from the better questing book. You may have to go into controls and look for Quest Log and key bind it to another key, I think it's default conflicts. That will tell you what exactly the NPC's are looking for. You may have to show her the ingredients first before assembling them. As for bats, check the empty houses near Mary's I have no problems getting them.  The only problem I found, is sometimes when I kill the bats, the wools wind up outside the house. (they fly through walls).

**Comment by satanKami** [comment]
just so you know there isnt many auto complete most of items need to checked by npc and it takes time for the mod to know you did something
