### ISSUE TITLE
The new Update 1.8.0.1 unable to download correctly.

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#61]
I have been trying to download the pack into a new instance for testing. I keep getting only the amnesia mods in it.  I have yet to be able to download it completely. I have deleted all the other instances and backup files and tried it as a new complete install and I get the same thing. I wanted to double check with you before I put a support thing in ftb forums. I saw someone else was having difficulties with partial pack downloads in twitch but with another pack.

**Comment by teagan75** [comment]
Yes. This has been an issue with other packs and is a Twitch Launcher issue. Some have found success dl an older version and then updating. All have solved it by deleting and reinstalling the launcher. I would send them a report regardless. Reinstalling the launcher should not delete your instances

**Comment by Ladysarajane** [comment]
I have tried to Uninstalling and reinstalling the launcher and surprise, surprise, my uninstall is missing. I have put a support ticket in, not only for the incomplete download, but for the missing uninstall script. I think the last couple updates to the launcher went buggy.

**Comment by teagan75** [comment]
I agree and it sucks ☹️

**Comment by Ladysarajane** [comment]
I did try to install an older version (1.7.1) and was going to try to upgrade it to current, but the same thing happened.  So I am out of testing until this problem is resolved.

**Comment by teagan75** [comment]
You could try one more thing. Open the launcher and at the top left are 3 lines. Click on it and go to files and settings. Then select run as administrator.
![launcher issue](https://user-images.githubusercontent.com/12485764/39932209-25574e00-5505-11e8-9f17-6dd2d5bf62da.png)

**Comment by Ladysarajane** [comment]
Yeah, I had that already. I installed twitch over my currently twitch app and I was able to uninstall it. I reinstalled it and the same thing is happening with modpacks. Only about 4-5 of them are downloading.

**Comment by teagan75** [comment]
It has been frustrating and random too. I am sorry ☹️

**Comment by Ladysarajane** [comment]
Nothing for you to be sorry. I blame the May 8th twitch update! I just can't find a work around.

**Comment by teagan75** [comment]
Yeah. I use the launcher to get packs and move them over to MultiMC but now getting packs is broken 😩

**Comment by Ladysarajane** [comment]
Yeah it is all packs. I posted in the support in ftb forums, but my post needs approval and apparently  no moderators have been on since 11am est. Frustrating.

**Comment by Ladysarajane** [comment]
By some weird miracle of uninstalling and reinstalling Twitch several...several times....and clearing the Twitch cache BEFORE deleting and AFTER installing I finally got it to work. This is no longer relevant for me right now. The downloads before had all the configs of all the mods....just not all of the mods...really odd. FTB has not approved my post yet in support. I wanna see how long it takes them. Not really sure why my posts have to be approved after all this time I have been there.  You could leave this issue here for a while in case others have problems with it.

**Comment by LadyGrelka** [comment]
It seems that you might have to start putting up your packs on the MultiMC launcher, by the way, thanks for the help you are giving me in the comment section of Modii's first episode of this pack on his channel that we have high-jacked :)   :P  Just  note to all on here, Teagan is putting up a zip file for us to download and use with the MultiMC launcher, isn't she great, *gives Teagan a hug and a cheesecake*

**Comment by teagan75** [comment]
Ok you can now add a new instance in MultiMC. On the left you will see import from a zip. There will be a section to add in a url. Put this there and let it install for you :D

https://minecraft.curseforge.com/projects/teagans-guide-to-witchery/files/2568556/download

**Comment by angelichime2** [comment]
I'm trying to install it from the twitch app more than twice and its not working.

**Comment by teagan75** [comment]
You need to contact Twitch about this or dl the MultiMC version on the Witchery curseforge page

**Comment by satanKami** [comment]
worked for me...
try older version?
or maybe its twitch no download error

**Comment by Ladysarajane** [comment]
@angelichime2 , Try doing what I did. Uninstall Twitch, install it again and repeat if necessary. (Took me about 5 times of uninstalling, and reinstalling. I know the last time I did it, I did reboot the computer after uninstalling and before I reinstalled and as Teagan said you could try the MultiMC version if this doesn't work.  

My personally feeling on this, is I have had Curse for awhile and one of the updates didn't do what it was suppose to and Curse had conflicting instructions. If your uninstall is missing, Install the program, then uninstall it. For me just messing with the Twitch launcher program DOES NOT mess with any installed instances of Minecraft that I had and what was working.
