### ISSUE TITLE
Father Donavich Quest Bug

### ISSUE THREAD

**Issue by chaserox5** [teagan75/Witchery#64]
I'm returning to father donavich with my information I gathered from the death house, but I can't seem to enter dialogue with him and it remains incomplete. I tried to force complete the quest with a command, "/noppes quest finish <username> 21" but that's also not working.

**Comment by satanKami** [comment]
did you talk and finish the talk with the sisters?

**Comment by chaserox5** [comment]
I'm not sure? I believe so. I've finished all the quests leading up to having to leave the death house through the secret exit and return to father dunavich with the info we got from the death house. But for some reason I can't enter dialogue with him and the quest doesn't complete when I return to the church.

**Comment by chaserox5** [comment]
Like I've found the ritual room abd everything.

**Comment by satanKami** [comment]
what the quest book and npc questline tell you?

**Comment by chaserox5** [comment]
The quest book just said to take the items and information I got from the death house, return to the church, and talk to the priest. However I seem to be missing a written book? In the quest tab of my inventory it says 0/1 for a written book. 🤔

**Comment by satanKami** [comment]
in thr questline it told you to find an hidden book... its somewhere in the
deathhouse

**Comment by chaserox5** [comment]
Is it not the book taken from the secret room in the library? 🤔

**Comment by teagan75** [comment]
Did you loot the corpse?

**Comment by satanKami** [comment]
​well he said he when to the exit​

2018-05-13 21:33 GMT+03:00 teagan75 <notifications@github.com>:

**Comment by chaserox5** [comment]
I looted the corpse to the left of the altar in the ritual room buuuuuut I was in creative mode when I did it (The monster kept killing me) so that may have bugged it out.

**Comment by teagan75** [comment]
Being in creative would not have affected it. Missing a part or the quest not triggering properly. I will see about giving you the command if you think you followed the quest book and it just didn’t trigger

**Comment by Ladysarajane** [comment]
Make sure you have the magic circle book, Potion of exhale of the horned one, potion of breath of the goddess and the rowan wood, It triggered for me fine.

**Comment by teagan75** [comment]
What Ladysarajane said. But if you didn’t get those in the first place something else went wrong

**Comment by Ladysarajane** [comment]
@teagan75  You know I was kinda surprised I didn't have to take the stone bricks to him for it to trigger. It is what you get from the adventurer's body for part of the altar. I was taking things one at a time to Donavich that I obtained and that is what I found. 
Will the attic portal open without finding the secret room? That is the other thought I had. If you need me too, I will try that in another world if chaserox5 can't get it to trigger.

**Comment by teagan75** [comment]
The attic door should not open until after the secret room. I also cannot remember what triggers the quest completion. I will have to did deep. Today is my Witchery pack work day so I will be fixing things hehe

**Comment by teagan75** [comment]
chaserox5, if you are still having trouble and have completed the Poppet quests with Mary, run the command: /noppes quest finish [your IGN] 25

btw this is what the quest is asking for
![quest item](https://user-images.githubusercontent.com/12485764/40008645-6e7b0510-5765-11e8-98e7-ff3ff899d97d.png)

**Comment by chaserox5** [comment]
AHA! THANK YOU SO MUCH! So turns out I'm a dunce. I had moved the diary into my pack. So it wasn't triggering. Thank you so much!

**Comment by teagan75** [comment]
No problem. Glad I could help.
