### ISSUE TITLE
Vita in 1.8.0.1 Question

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#65]
Okay, in killing brutes and servants and wolves, I have been getting Vita's instead of the essence. Is this what is suppose to drop now? I am not familiar with that mod vita comes with. Will it be useful later in quests?

**Comment by teagan75** [comment]
Those are not important and I will work on disabling them

**Comment by Ladysarajane** [comment]
Thanks Teagan. Glad I asked. I will trash them.

**Comment by teagan75** [comment]
fixed in v1.8.1
