### ISSUE TITLE
Possible Quest Bug?

### ISSUE THREAD

**Issue by chaserox5** [teagan75/Witchery#66]
I'm working on the Vallaki quest line, and am trying to complete "custom brews." I've gotten Luvash to explain the basics of brewing, I've gathered the mandrake, apple, and artichoke bulb. However, when I drop the ingredients in the cauldron and get my brew of harvest, the quest doesn't recognize that I have the brew in my inventory. I try to hit 'detect/submit' and nothing happens. 🤔

**Comment by satanKami** [comment]
ammm try gunpowder instand of the water one...
it need to be in 100% order or it will be another potion

**Comment by teagan75** [comment]
Yeah try the gunpowder. Anytime it asks for artichoke use gunpowder.  I fixed all those quests and somehow they didn’t save. It will be fixed next update I hope hehe

**Comment by chaserox5** [comment]
Yep yep! For some reason the gunpowder dispersal is considered a different potion than the artichoke. That fixed it! Thanks!

**Comment by teagan75** [comment]
fixed in v1.8.1
