### ISSUE TITLE
Returning Emil Quest Bug

### ISSUE THREAD

**Issue by chaserox5** [teagan75/Witchery#67]
While doing the werewolf quest line, I found Emil in the ravenloft prison, found the key to the prison, and unlocked his door. Now I have to use the soul crystal on him, and take him back to the pack. However whenever I use the crystal on him, it doesn't recognize the crystal in my quest book.

**Comment by teagan75** [comment]
That is a bug and will be fixed next update. For now try running the command /noppes quest finish [your IGN] 162

**Comment by chaserox5** [comment]
That did it! Thanks!

**Comment by teagan75** [comment]
fixed in v1.8.1
