### ISSUE TITLE
Bug With Luvash's brew questline?

### ISSUE THREAD

**Issue by chaserox5** [teagan75/Witchery#68]
Luvash wanted me to brew a brew of flames with a gas dispersal. I followed the recipe to the letter, and got the Brew, but my quest log isn't recognizing it.

**Comment by teagan75** [comment]
Does this one also ask for water artichoke? But needs gunpowder?

**Comment by satanKami** [comment]
some potions need power?(alter)

**Comment by teagan75** [comment]
I thought they all needed altar power. I will be recording my Witchery today and will check the quest. The newest update should fix this but you will need the command to stop and start the quest again.

**Comment by chaserox5** [comment]
🤔 Well I didn't think the gunpowder/water artichoke thing would necessarily be an issue because this brew requires wool of bat specifically.

**Comment by teagan75** [comment]
Your right. No artichoke/gunpowder but it must have been something else. If you have updated to the newest version, run the command /noppes quest stop [your IGN] 202 then run the command  /noppes quest start [your IGN] 202 to see if it is fine now.

**Comment by teagan75** [comment]
Any update on this issue?
