### ISSUE TITLE
"Become A Werewolf" quest bug.

### ISSUE THREAD

**Issue by chaserox5** [teagan75/Witchery#69]
In the kingdom of Barovia werewolf questline, after rescuing Emil from Ravenloft Prison, and returning him to Zuleika, I'm supposed to receive the gift of lycanthropy. Under the objectives for the quest it just says "The Gift III - Unread." Zuelinka won't talk to me, and I wasnt given a book to read. So I'm unsure if this is a bug or just my own ineptitude. P.S. Thank you for all the hard work you put into this pack! I'm really digging it!

**Comment by teagan75** [comment]
You should have gotten a hellhound head and a coven witch spawn egg. There is a ritual circle on top of the den but you will need altar power. You have to perform the ritual yourself as there is no way to make you a werewolf other than being bitten. Curse of the Wolf should have opened up in your quest book to explain this further

**Comment by chaserox5** [comment]
🤔 None of that happen. I didn't get any of the items. And I don't believe curse of the wolf opened up. Very strange.

**Comment by teagan75** [comment]
This will be fixed in the next update.
