### ISSUE TITLE
1.2-alpha - Father Donavich quest order

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#7]
After visiting Father Donavich's son and the Dead House but before we had continued the alter quest with Mary, Father Donavich had dialog about the circle magic and gave me a Distillery book (we now have 14 of those :D)

**Comment by teagan75** [comment]
He is spamming them?

**Comment by LindaJuffermans** [comment]
He just gives the same dialog (only the last part of it, btw) and the book every time I right-click him; until we've actually continued the altar quest with Mary.

**Comment by teagan75** [comment]
This is an easy fix 😁

**Comment by LindaJuffermans** [comment]
After showing the distillery to Father Donavich we started the chalk questline. As instructed we performed the Rite of Sanctity, we returned to him but he's back on the "Was Mary able to help at all" (from before the distillery).

According to the quest book he should have told us about the talismans but he hasn't; still we did the Rite of Binding but with the "Circle Talisman (Small Ritual)" in our inventory Father Donavich is still stuck on the "Was Mary able to help at all" line. I tried showing the distillery to him again but that hasn't helped. We're stuck on the "Talismans" quest for now.

**Comment by teagan75** [comment]
Fixed the book spam for version 1.3

Also, the other issue should be fixed as well since I rearranged Mary’s dialogues for the next version. Will keep this open if it still is a problem.

**Comment by satanKami** [comment]
father wont trigger stuck on dialog curing doru quest-1.2

**Comment by teagan75** [comment]
Are you on version 1.3?

**Comment by satanKami** [comment]
no it's s 1.2 comment

**Comment by teagan75** [comment]
I fixed all the bugged quests. I did a fresh play through to see what was actually happening so I think it will work now in version 1.4
