### ISSUE TITLE
Quest Line Bugs

### ISSUE THREAD

**Issue by Rickyromeroa** [teagan75/Witchery#71]
I have gotten stuck on 2 different quest lines for the Village if Barovia section. I completed all of the poppets for Mad Mary but whenever I click on her she still wants to talk about the poppets and doesnt move on to the next quest of finding her daughter. Also, for The Attic quest, i found it and the secret door but it wont let me detect/submit the quest so I can move on to the next quest in the line.

**Comment by satanKami** [comment]
mad marry quest end for now with the puppet
as for the death house you missed something 
check npc quest log and the quest book to see what you missed

**Comment by Ladysarajane** [comment]
If you have completed all the poppets and completed everything in the NPC quest book for the poppets (separate from Better Questing Log book) with Mary, Don't worry about Mary talking about the poppets for now. She will advance after you do some quests for Father Donavich. 

As for the Death House, did you find the secret room, when you got the Key for the children's room....there is a book in there you need to obtain.

**Comment by Rickyromeroa** [comment]
Yeah i found the book but it never told me quest completed, it just moved
me onto the basement thing with all the coffins

**Comment by Ladysarajane** [comment]
What exactly is not completed in the Better Questing Book?

Did you talk to the children in the attic

**Comment by Rickyromeroa** [comment]
"THE ATTIC"

**Comment by Ladysarajane** [comment]
If you have completed both locations under the attic and they show they have been completed, then you need to go into HQM edit mode and complete that task

**Comment by Rickyromeroa** [comment]
How do i do that?

**Comment by teagan75** [comment]
That is complicated. Go into the quest book and press Shift while hovering over the quest. You will see a number. 

Run the command /bq_admin complete {#}

**Comment by teagan75** [comment]
If you need more help, reopen this issue.
