### ISSUE TITLE
Alpha 1.8.0.1 Burgormeister Mansion missing blocks (minor)

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#72]
Don't know how, First time going through the mansion on this world. On the second floor I think servant quarters there are missing wool blocks to one of the rooms
![2018-06-05_13 51 59](https://user-images.githubusercontent.com/34258851/40993790-85e31fa2-68c8-11e8-9c9a-a570862376b8.png)

**Comment by teagan75** [comment]
That’s strange

**Comment by Ladysarajane** [comment]
I looked in my previous instances and the blocks were missing there too. Just never raided the servants quarters off the kitchen before.

**Comment by teagan75** [comment]
This is fixed for the next update.
