### ISSUE TITLE
Game Crashed; Causing my laptop to froze T^T

### ISSUE THREAD

**Issue by angelichime2** [teagan75/Witchery#75]
I was able to install/download the pack but when I download the server zip and begin to play it on the twitch app for it, the game crash and my laptop froze. I really want to play it even though there is a lot of jumpscares in the modpack. 

I also did it with the minecraft pe that i have one before i download the twitch app to my laptop it also crashes too. Don't know whats going on but it keeps freezing my laptop every time I play it on the twitch app.

**Comment by teagan75** [comment]
I can’t help you without a crash report that you find in your instance folder. 

Secondly, the file you are referring to is not a server file. It is for those who use the MultiMC launcher. So unless you know how to install a custom profile on Twitch don’t try it. I would just contact Twitch help.
