### ISSUE TITLE
Barovia isn’t there

### ISSUE THREAD

**Issue by SteezyJesus** [teagan75/Witchery#76]
I loaded up the pack for the first time and went to do the first location quest but there was no “gravel path” and the quest led me to nowhere, in the middle of a forest.

**Comment by SteezyJesus** [comment]
I’m a big dumb idiot head and didn’t download the map on the main menu, ignore me...

**Comment by teagan75** [comment]
Well the map on the main menu is only an update. If it still isn’t working, move the template folder (inside your Minecraft instance/folder) into your saves folder.
