### ISSUE TITLE
Reflect brew not being recognized.

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#77]
I was doing the Brew of reflect that Luvash wanted, and I got all the items and threw them in the cauldron in ordered listed in the quest book and I obtained the Brew of Reflecting IV and now the quest book and Luvash will not recognize it. Any ideas? Attuned stone was charged and I did the ritual to get the spectral dust. Not sure what is going on. Sorry I haven't been testing Real life has been interfering with me having to have tests, but I have been LOVING Modi 101 doing this pack. He really makes me laugh. You put those squeaky sounds in just to annoy him the "porky" guy.  I love it!!!

**Comment by teagan75** [comment]
Can you do me a favor and pull the items out of creative and use gunpowder instead of water artichoke. If that doesn’t work I will have to see if I forgot something

**Comment by Ladysarajane** [comment]
Uh...kinda confused. The recipe in the quest book doesn't call for gunpowder or water artichoke
![2018-08-09_20 05 53](https://user-images.githubusercontent.com/34258851/43932066-0ee1c068-9c10-11e8-9362-48dcd817664a.png)

**Comment by teagan75** [comment]
Ah ok. I will have to fix it somehow. In custom npcs the item required for completion should have ignored meta data. I may have missed it. I will look up the quest number tomorrow and give you the command to auto complete it.

**Comment by Ladysarajane** [comment]
Okay here is the pic of the brew I received
![2018-08-10_10 08 42](https://user-images.githubusercontent.com/34258851/43966373-bb6d9594-9c8f-11e8-8d26-d85da029b61c.png)
.

**Comment by Ladysarajane** [comment]
Whoops! Somehow I accidentally closed the issue. Is this correct brew that should have been made?

**Comment by teagan75** [comment]
yeah that is the one. not sure why it didn't take it but the potions are trial and error with the quest book D:
run the command /noppes quest finish [your ign] 203

**Comment by Ladysarajane** [comment]
Okay, that cleared it in the Better  Questing Book, but not in the NPC quest log. I showed Luvash the potion after completing the command, but he  just shows me his store, doesn't even talk about the potion. The quest is still active in the NPC quest log book. Is there another potion after that, that the quest book is looking for?

**Comment by teagan75** [comment]
No. It’s probably still in there as a glitch. Custom npcs gets glitchy when you use the commands. If the questbook cleared you are fine. There isn’t another potion. I think that ends his quests in Better Questing

**Comment by Ladysarajane** [comment]
Okay, wanted to make sure there wasn't anything else to do in that quest line. So I am done with Luvash completely then. Okay I have another question. Do you give blaze seeds as a reward anywhere? I find myself in need of blaze powder to make more null catalyst to make silvered hunters clothes, (mine were damaged and I cannot upgrade them) and making more catalyst requires lots of blaze powder. I know there is another recipe involving rosin, but that requires cutting LOTS of spruce trees among other ingredients.

**Comment by teagan75** [comment]
Not sure if I give blaze seeds. Would you suggest I give it as a reward for making the hunter armor? I will need to look through my quests again hehe

**Comment by Ladysarajane** [comment]
Yes I would add them as a reward somewhere....I  damaged  my first set and now I have to remake them for the Silvered Hunter clothes, And null catalysis isn't cheap to replicate. I thought you could mend the Hunter clothes which would have made it do able, but I couldn't find a way to mend them. Modi obtained the silver witch hunter clothes quest, which he hasn't completed yet, but he hasn't triggered the making of the witch hunters clothes in Rictavio"s tower. (but he broke a glass to rob it of the chalice, LOL)  Not sure if he will run into the same problem of having to make them twice too. He is looking for the withered skull but hasn't found it in the storage room yet, but he talked to Victor. 

If you don't have blaze seeds as a reward now, maybe add them in at the end of the Rictavio's Tower quest after making the first set of clothes, or sneak them in somewhere in with making the silver vats, before having to make the second set of hunter clothes. 

Another question, I was going to do the cure Doru quest and perform the ritual, It told me I need the cat familiar for the quest, (If I am doing it right). If I get a cat familiar, I lose my owl as a familiar? If I have my owl in a soul stone, will that break and I lose that owl? I hope I won't, so I can rebind the owl later to do the bodega brew.

**Comment by teagan75** [comment]
I know you can only have one familiar at a time. Also, it is weird he got the silver hunter armor because it’s suppose to be gated behind the regular hunter armor. Can you not use regular leather in an anvil to fix the armor?

**Comment by Ladysarajane** [comment]
I know he got the silver vat quest and did it. I will have to re watch that one, cause I thought it talked about the silver hunters clothes.  *bangs head on keyboard" I was trying to mend it with nullified leather....not plain leather.

**Comment by teagan75** [comment]
The vat quest is not gated. And it’s okay 😁 Maybe I should add in a blurb about it.

**Comment by Ladysarajane** [comment]
The blurb might be good at the point of making the silver hunter clothes. Could've sworn I tried leather before I started making null catalyst but I obviously didn't. I did rewatch Modi's video and it is gated. (The clothes not vat).

**Comment by teagan75** [comment]
ok the reflect brew should be fixed and in the next update. I forgot to add one item to the list in the quest book.
