### ISSUE TITLE
1.2-alpha - Mad Mary altar and poppet quests

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#8]
We moved towards the Father Donavich and altar questline before completing the poppets; after creating the altar we went to Mad Mary but she only wanted to talk about poppets. After we finished the fire poppet quest, she had dialog about the altar quests - we're no longer able to do the other poppet quests with her and thus not able to do the "Finding Gertruda" quest.

Perhaps "Blood of the Vine Tavern" should require all poppet quests too.

**Comment by teagan75** [comment]
Hmmm I may have to rearrange and prioritize dialogues a bit. However I do have limitations with custom npcs

**Comment by LindaJuffermans** [comment]
Forcing people to finish the poppets before going into the Father Donavich quest might fix it.

**Comment by teagan75** [comment]
Ok I rearranged the dialogues to try and keep things a little less linear. 

Without starting over, and once I release the new version, you can use the NPC wand to delete the current Mary and use the Mob Cloner to place the new Mad Mary down. That way you can see if the other poppet quests show up.

**Comment by LindaJuffermans** [comment]
![clone](https://user-images.githubusercontent.com/31929183/33732947-6ebd36f0-db88-11e7-8297-bf7d5bff7a43.jpg)

![no-mary](https://user-images.githubusercontent.com/31929183/33733099-e6422c9e-db88-11e7-8896-a1a0c6e7ab71.jpg)

Am I looking at the wrong GUI? I mean... it's nice and quiet without her balling but I fear we'll miss her... 😉

**Comment by teagan75** [comment]
No.....sigh.....I just tried cloning her again and it won't save for whatever reason :(

**Comment by teagan75** [comment]
I have reported this bug to Noppes

**Comment by teagan75** [comment]
As far as the other issues, I fixed all the bugged quests. I did a fresh play through to see what was actually happening so I think it will work now in version 1.4
