### ISSUE TITLE
Start without questbook.

### ISSUE THREAD

**Issue by Gretchen317** [teagan75/Witchery#81]
I start with a lantern, backpack, sword, and some apples. There is only a sleeping back in the box. I created a new world 3 times to see if that would fix it, and it did not. I download the map and added it to the world I created. Am I missing something?

**Comment by satanKami** [comment]
nope that is it.. press tab or ~ to see the quest book
have fun ^-^

**Comment by Gretchen317** [comment]
Thank you! ~ did the trick. :)
