### ISSUE TITLE
1.2-alpha - Fire poppet quest

### ISSUE THREAD

**Issue by LindaJuffermans** [teagan75/Witchery#9]
In the quest book, the fire poppet quest requires 2 wool of bat and 2 ink sacs; that should be 2 wool of bat and 2 ember moss.

**Comment by teagan75** [comment]
Weird. Is that in the questbook? Or is Mary wanting the wrong items cause on Mary the quest requirements are correct

**Comment by teagan75** [comment]
Never mind I just reread that 😝

**Comment by teagan75** [comment]
Fixed for version 1.3
